### ISSUE TITLE
GPU on Bessemer

### ISSUE THREAD

**Issue by tartarini** [rcgsheffield/sheffield_hpc#1042]
On this page:
[gpucomputing bessemer](https://docs.hpc.shef.ac.uk/en/latest/bessemer/GPUComputingBessemer.html#gpucomputing-bessemer)

`srun --nodes=1 --gpus-per-node=1 --pty bash`

generates this error:
`xxxt@bessemer-login1 ~]$ srun --nodes=1 --gpus-per-node=1 --pty bash
srun: error: Unable to allocate resources: Requested node configuration is not available`

srun proceed with the scheduling if --mem flag is specified

**Comment by willfurnass** [comment]
@tartarini Yes, the documentation currently fails to mention that you need to specify a Slurm 'partition' and a Slurm 'qos' to access the public GPUs in Bessemer (see PR #1045).

**Comment by willfurnass** [comment]
Also, be aware that the public GPUs in Bessemer are currently very busy so it's unlikely you'll be able to get on-demand interactive access.
