### ISSUE TITLE
On (non-py)torch pages note that most folks will want to use pytorch instead?

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1051]
As suggested by @adityagilra

@twinkarma What do you think?

**Comment by twinkarma** [comment]
Yes that's probably a good idea, also the torch repo hasn't had a commit since last year so do we consider that project pretty much abandoned in favour of PyTorch now?

**Comment by willfurnass** [comment]
@twinkarma Yes, that adds weight to the argument for pointing people at pytorch.
