### ISSUE TITLE
Bessemer: Install Clang Toolchain

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#1069]
Would it be possible to get clang toolchain installed on Bessemer?

**Comment by willfurnass** [comment]
Any version in particular?  See https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/c/Clang

**Comment by ptheywood** [comment]
No version requirement so most recent?

**Comment by willfurnass** [comment]
I'll try building Clang-10.0.0-GCCcore-8.3.0.eb then.  Out of curiosity, what are you wanting it for?

**Comment by ptheywood** [comment]
The original code i'm working with only supports clang by default (although some modifications make it gcc compat, but with slightly different results, probably RNG related?).
