### ISSUE TITLE
R versions on Bessemer

### ISSUE THREAD

**Issue by SimonCMills** [rcgsheffield/sheffield_hpc#1110]
As far as I can tell there is only a single version of R installed on Bessemer (3.6.2-foss-2019b). This won't run some of the packages I need (namely cmdstanr). Is it possible to add additional versions? On Sharc I've been using 3.6.3/gcc-8.2.0 without any issues. 

Thanks, 
Simon

**Comment by jkwmoore** [comment]
Ah, we've just noticed this request - we will look into this shortly.

**Comment by SimonCMills** [comment]
Thanks- any update on this?

Best wishes,
Simon

**Comment by jkwmoore** [comment]
Hi Simon,

We've had quite a busy week dealing with quite a few urgent priority issues - I am planning on cracking on with this today - I will update you when we have a testing build available in the staging area of easybuild.

Cheers!

**Comment by SimonCMills** [comment]
Not a problem at all- thanks!

Cheers,
Simon

**Comment by jkwmoore** [comment]
Hi Simon,

A build for 4.0.0 should now be available in staging for testing - it has been built in the same way as the previous version: https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/R.html

That is to say - "with EasyBuild 4.3.1 minus any of the configuration to install 765 packages from CRAN (i.e. just base R was installed)."

To load this module and use this you can do the following - 

Make the staging modules accessible with the modules command:

`module use /usr/local/modulefiles/staging/eb/all/`

Load the module:

`module load R/4.0.0-foss-2020a`

If you could get back to us with a confirmation that the module is working correctly we can move it out of staging :)

Cheers!

**Comment by SimonCMills** [comment]
I can install all the packages I need and run them without issue, so seems
to be working well.

Thanks for your help- much appreciated.

Cheers,
Simon

**Comment by jkwmoore** [comment]
I will look at getting this moved out of staging and the documentation adding shortly then.

Thanks.

**Comment by jkwmoore** [comment]
https://github.com/rcgsheffield/sheffield_hpc/pull/1116 addresses this.

**Comment by jkwmoore** [comment]
Now merged - docs should reflect this update shortly.
