### ISSUE TITLE
[Enhancement] Add exit code diagnosis to troubleshooting

### ISSUE THREAD

**Issue by jkwmoore** [rcgsheffield/sheffield_hpc#1119]
It might be an idea to add the exit codes from SGE to the troubleshooting steps?

https://docs.oracle.com/cd/E19957-01/820-0699/chp11-3/index.html

Specifically exit 128+9 = 137 out of resources job kill.

**Comment by jkwmoore** [comment]
Also possibly for SLURM:

https://wilsonweb.fnal.gov/jobReasonCodes.shtml

**Comment by willfurnass** [comment]
May be able to point users to man pages for this.
