### ISSUE TITLE
Add Miniconda installation documentation to the Python pages

### ISSUE THREAD

**Issue by jkwmoore** [rcgsheffield/sheffield_hpc#1124]
This needs adding (mostly cut and paste from a ticket) but should ideally be put onto the existing Python Anaconda pages as a header section separated with a link from each cluster's top level software page.

**Comment by jkwmoore** [comment]
Example spiel below:

You can see the available installers here: https://docs.conda.io/en/latest/miniconda.html

I will be using the Python 3.8 installer as the example. You should probably install this to your data directory i.e. /data/$USER/miniconda or a similar subdirectory as your home directory has limited space (ShARC-10GB and Bessemer-100GB) and conda packages can pile up quickly. Running out of space is sub-optimal!

#Download the installer
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

#Check the sums match with those listed on the website
sha256sum Miniconda3-latest-Linux-x86_64.sh

#Make the file executable
chmod +x Miniconda3-latest-Linux-x86_64.sh

#Run the installer - Make sure to choose your data directory  and subdirectory i.e. /data/$USER/miniconda (don't make this directory prior to the installer as it makes the directory itself when you supply it with a directory path.)
#!!!Make sure you do not initialize Miniconda as this will break you loading other Anaconda modules on the cluster!!!

./Miniconda3-latest-Linux-x86_64.sh

#Make a modules folder for yourself
mkdir /home/$USER/modules

#Make a module file for the install you just made
nano /home/$USER/modules/minconda

#Put the correct stuff inside said module file - i.e. paste the below into the file - if you are not using the miniconda subdirectory in your data folder - make sure you change the below - also note that this file is in TCL not bash - so environmental variable handing is different from the normal $USER for username:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

```
#%Module10.2#####################################################################
##
## User Data Directory Miniconda module file
##
#  Updated by JKWMoore 10/12/2020
#
#
################################################################################


proc ModulesHelp { } {
        global version

        puts stderr "Makes a user's personal install of Miniconda in their data directory available."
}

module-whatis   "Makes a user's personal install of Miniconda in their data directory available."

# module variables
#
 set MINICONDA_DIR     /data/$env(USER)/miniconda/bin

prepend-path PATH $MINICONDA_DIR
```

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

At this point you can use the modules use command to make your own modules available to be loaded:

module use /home/$USER/modules

If you want to skip doing the above everytime you login, you can add this line to the .bashrc file in your home directory!

And now you can load the module whenever you need it with (assuming you named the module file miniconda):

module load miniconda

From this point you can install the packages as you have been doing prior with our main Anaconda modules - as a side note - I would avoid loading any two modules of the same type at the same time - i.e. do not load our anaconda modules and miniconda at the same time.

**Comment by davidwilby** [comment]
Can confirm that this works and I approve of adding it to the docs.

**Comment by jkwmoore** [comment]
> 
> 
> Can confirm that this works and I approve of adding it to the docs.
> 
> It's also worth saying that the only reason I was doing this is to use a newer version of python..

So was the caller IIRC ;)

**Comment by jkwmoore** [comment]
Now pending PR at https://github.com/rcgsheffield/sheffield_hpc/pull/1142

**Comment by willfurnass** [comment]
@davidwilby Yes, the rationale for installing one's own miniconda vs just using the central install(s) needs to be clear in the docs.
