### ISSUE TITLE
Request for new software - Bedtools

### ISSUE THREAD

**Issue by hgfryer** [rcgsheffield/sheffield_hpc#1157]
Hello,

I need to use bedtools to handle large genomic files, would it be possible to install this software on sharc?

Kind regards,
Hannah

**Comment by jkwmoore** [comment]
Hi there,

I am in the process of finishing the installation for ShARC - I will update you when this finished.

As Bessemer has a nicer build system it has already finished and you can access BEDtools 2.29.2 which is currently in the staging directory.

You can access the staging modules on Bessemer by making the staging directory modules available:

`module use /usr/local/modulefiles/staging/eb/all/`

Then loading the module with:

`module load BEDTools/2.29.2-GCC-9.3.0`

To remove the module: 

`module unload BEDTools/2.29.2-GCC-9.3.0`

To remove staging directory modules from the modules system:

`module unuse /usr/local/modulefiles/staging/eb/all/`

Please give this a test and I will move the module into our live modules.

Cheers.

**Comment by jkwmoore** [comment]
BEDTools 2.30.0 is now available on ShARC and can be loaded with:

`module load apps/bedtools/2.30.0/gcc-8.2-cmake-3.17.1`

Please give this a test for any issues (I have not run the make check).

Thanks.

**Comment by jkwmoore** [comment]
*Note documentation is to follow.

**Comment by hgfryer** [comment]
Thank you very much, I have tested it and it works.

**Comment by jkwmoore** [comment]
Can you clarify which install? Both?

Thanks!

**Comment by hgfryer** [comment]
Both worked perfectly. Thank you very much for your help!

**Comment by jkwmoore** [comment]
Fantastic, many thanks! I will get this added to our docs tomorrow then close the ticket.

**Comment by jkwmoore** [comment]
This is now in the live modules for Bessemer.
