### ISSUE TITLE
Installing libsndfile

### ISSUE THREAD

**Issue by Mattias421** [rcgsheffield/sheffield_hpc#1168]
Hi,

I am using a lipreading neural network program in python for my dissertation but I cannot get it to run because it requires libsndfile which I believe must be installed on the OS. Unfortunately I am unsure which version is specifically required.

Would it be possible to have this installed?

Thankyou kindly,

Mattias Cross
mgcross1@sheffield.ac.uk

**Comment by jkwmoore** [comment]
I will take a look at this shortly. Which cluster do you need this on?

**Comment by Mattias421** [comment]
I am using ShARC, thank you :)

**Comment by willfurnass** [comment]
Hi @Mattias421.  See https://docs.hpc.shef.ac.uk/en/latest/sharc/software/libs/libsndfile.html

**Comment by Mattias421** [comment]
Thank you so much, @willfurnass! This is fantastic and a great help to my research :)

**Comment by jkwmoore** [comment]
Cracking - I'll close this one out then.
