### ISSUE TITLE
request for Altair Flux for machine 

### ISSUE THREAD

**Issue by wzhu24sheffield** [rcgsheffield/sheffield_hpc#1251]
Hi, if it is possible to get Altair Flux on Bessemer/sharc?

**Comment by jkwmoore** [comment]
I've asked our licensing team if we have a license for this software which does not appear to be the case. If you have your own license and access to the installation files you are allowed to install the software to your personal directories.

I would recommend using the your own folder in the data filestore if you do so.

Further guidance for this can be found here:

https://www.sheffield.ac.uk/it-services/research/hpc/using/install

**Comment by jkwmoore** [comment]
I have further been advised that if you would like to look into this further in terms of getting licenses for using the application that you can open a ticket with the helpdesk and ask for fill in a non-standard request form for this to go to your departmental business relationship manager.

You will be able to open a ticket by sending this request via email to it-servicedesk@sheffield.ac.uk

Thanks,

James.
