### ISSUE TITLE
requirements.txt not used by GitHub Actions workflow

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1261]
ReadTheDocs uses it but our GHA Workflow that uses https://github.com/rcgsheffield/sphinx-action doesn't.  We should be consistent here, ideally by ensuring our GHA environment is created using`requirements.txt`.

**Comment by jkwmoore** [comment]
See https://github.com/rcgsheffield/sheffield_hpc/pull/1262 for why ;_;

**Comment by willfurnass** [comment]
Sorted via #1265
