### ISSUE TITLE
Port a more complete set of instructions on file transfer

### ISSUE THREAD

**Issue by jkwmoore** [rcgsheffield/sheffield_hpc#1327]
See: https://www.sheffield.ac.uk/it-services/research/hpc/using/access

Needs porting to: https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html

**Comment by jkwmoore** [comment]
To include:

- SCP / SFTP
- rsync
- rclone?
- Filezilla (All Platforms)
- WinSCP (Windows)
- Cyberduck (Mac)

**Comment by willfurnass** [comment]
At present, we have:
 - Very limited info on https://docs.hpc.shef.ac.uk/en/latest/hpc/transferring-files.html
 - Which includes a dead link pointing at https://www.sheffield.ac.uk/it-services/research/hpc/using/access

Would be good to get some reference docs on transferring files to/from/between clusters added to this repo soon.  

See also #1123

**Comment by jkwmoore** [comment]
We need to refactor the whole lot. This should probably also cover best practise on transfers i.e. using the cluster network bandwidth and trying to avoid using any local machines.

**Comment by willfurnass** [comment]
Agree that is desirable to include such things.  Think we need to add this documentation incrementally to help prioritise the essentials.

Some useful material here: https://carpentries-incubator.github.io/hpc-intro/15-transferring-files/index.html
