### ISSUE TITLE
Add scheduler specific job debugging pages

### ISSUE THREAD

**Issue by jkwmoore** [rcgsheffield/sheffield_hpc#1344]
I think we would be well served by adding some specific pages for debugging under both schedulers. Probably a new page under the Troubleshooting menu item. (https://docs.hpc.shef.ac.uk/en/latest/troubleshooting.html)

I was thinking of something along the lines https://dv-zeuthen.desy.de/services/batch/troubleshooting/

We may also want to add an explicit / specific tab for "Monitoring your jobs" under the "Using the HPC Systems" (https://docs.hpc.shef.ac.uk/en/latest/hpc/index.html)

We can pull in includes from other pages i.e.  

https://docs.hpc.shef.ac.uk/en/latest/referenceinfo/scheduler/SGE/Common-commands/qstat.html
https://docs.hpc.shef.ac.uk/en/latest/referenceinfo/scheduler/SGE/Common-commands/qacct.html

https://docs.hpc.shef.ac.uk/en/latest/referenceinfo/scheduler/SLURM/Common-commands/sacct.html
https://docs.hpc.shef.ac.uk/en/latest/referenceinfo/scheduler/SLURM/Common-commands/squeue.html

**Comment by jkwmoore** [comment]
Where I have previously explained this roughly in emails:

- **failed** - tells you the error code and the reason why the job failed. See section 3 on this link:  https://dv-zeuthen.desy.de/services/batch/troubleshooting/
- **exit_status** - tells you the exit status of your batch script,  The exit code is the return value of the exiting program/script. For abnormally terminated jobs it is the signal number + 128. 
- **cpu** - the amount of CPU time consumed in seconds, this is a result of the [actual cpu time on said cores * the number of cores] . If this value is not approximately the [number of cores * wallclock  time] some of the cores are not fully loaded.
- **mem** - The integral memory usage in Gbytes seconds (aka plot a graph of memory vs time and this is the area under the line.)
- **ru_wallclock** - gives you the amount of time (as if you were watching your wristwatch) the job was running for. This does not include any queue time and is not the requested amount of time, it is only the actual time consumed when the job is running.
- **io** - the amount of input or output written/read from/to storage in GB.
- **iow** - the amount of time wasted waiting for Input/Output operations.
- **maxvmem** - this is the maximum RAM consumption (although technically this is vmem and slightly more complex.)
- **slots** - the number of requested cores.

**Comment by willfurnass** [comment]
This is a fab idea!  Like the structure on https://dv-zeuthen.desy.de.  We do have those sections on memory on the troubleshooting page; perhaps parts could be refactored into new content.

**Comment by jkwmoore** [comment]
Yes, I think a bit of a general refactor of the troubleshooting section is needed as it is quite hard to read at the moment.

That said, I am trying to think of how / if we can include some kind of flow chart like this but less sarcastic and hopefully interactive and just asks yes no questions then directs you to a specific section:

![image](https://user-images.githubusercontent.com/69149348/140324497-f0123f8d-3a79-446c-aeb8-14a61d660f26.png)

**Comment by willfurnass** [comment]
Totally agree that a hierarchy-less FAQ is hard to read and navigate.  Would just one level of hierarchy, possibly splitting the FAQ, do the trick for us?  How many clusters of FAQ Q&As do we need?

**Comment by jkwmoore** [comment]
It's certainly up for discussion, I think some form of quick clickable flow is needed.

e.g. 
1st question, what cluster are you having issues with? ShARC, Bessemer,Future cluster, all clusters
2nd Question, what kind of problem is it? My job failed, my job didn't start, how do I choose resources, how can I monitor my jobs, how do I login, I can't login etc...

But there's lots of room to discuss optimal pathing as it were. That and finding something we can even use to do this, native sphinx plugin, HTML injected to a page etc...?

**Comment by willfurnass** [comment]
How about set of refining questions where the responses are links to other Qs on the same page (via anchors) or e.g. a separate page containing a more detailed troubleshooting guide to area X?  Would be straightforward to implement with vanilla Sphinx.

**Comment by jkwmoore** [comment]
Ha, a "choose your own adventure" style book then. That would also work but could make the structure get a bit bloated? Devil is in the details!

**Comment by willfurnass** [comment]
Yeah!  Yes, would only work if we have a tight, concise triaging structure.

**Comment by jkwmoore** [comment]
This has also been partially addressed in the https://github.com/rcgsheffield/sheffield_hpc/pull/1359
