### ISSUE TITLE
Installation of STAR

### ISSUE THREAD

**Issue by ljharrison1** [rcgsheffield/sheffield_hpc#1376]
Hi! I would like to request the installation of STAR on bessemer. There is currently no alignment software available on bessemer to my knowledge, so this would be really useful for my work. Thank you!

**Comment by jkwmoore** [comment]
Please provide more info on what STAR is and I will have a look to see if we have an Easyconfig available.

Thanks!

**Comment by ljharrison1** [comment]
STAR is an RNA-sequencing alignment software (10.1093/bioinformatics/bts635). Here is the corresponding GitHub page: https://github.com/alexdobin/STAR/releases

**Comment by jkwmoore** [comment]
Thanks, having a look now.

**Comment by jkwmoore** [comment]
I've finished installing a test version to our staging area. Can you please give this a test by running the following commands to make it available:

module use /usr/local/modulefiles/staging/eb/all/
module load STAR/2.7.6a-GCC-9.3.0

If this is working to your satisfaction I will move this installation out of the staging area and eventually add some documentation.

Thanks!

**Comment by ljharrison1** [comment]
This worked really well! Thank you!

**Comment by jkwmoore** [comment]
No problem, I will add an issue to make sure this is moved out of staging / documentation is updated tomorrow morning.

**Comment by jkwmoore** [comment]
This is now available in the main area and can be loaded without the `module use` command.
