### ISSUE TITLE
parameter sweep in comsol

### ISSUE THREAD

**Issue by ghost** [rcgsheffield/sheffield_hpc#1379]
Dear All

I am a new user of Comsol. How I can do parameter sweep in the following form?

H changes from 0 to 4 then from 4 to 0.

Best regards

**Comment by jkwmoore** [comment]
Hi there,

I'm afraid we do not have any expertise with Comsol (nor do we have any training courses.) 

The info we do have is contained on our documentation page (https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/comsol.html) but this is limited to running it on the Bessemer cluster.

Thanks,
James.

**Comment by willfurnass** [comment]
Also, there's a mechanism built into the SGE job scheduler (ShARC cluster) and Slurm job scheduler (Bessemer cluster) called 'job arrays' (or 'array jobs' or 'task arrays') which you submit a set of jobs that are identical apart from the value of one environment variable.  Job arrays are often used for sensitivity analysis and may be useful here.  

Job arrays in SGE: https://docs.hpc.shef.ac.uk/en/latest/parallel/JobArray.html
Job arrays in Slurm: https://slurm.schedmd.com/job_array.html

**Comment by jkwmoore** [comment]
Please have a look at:

- https://uk.comsol.com/learning-center
- https://uk.comsol.com/learning-center/performing-parametric-sweep-study-comsol-multiphysics
