### ISSUE TITLE
it-servicedesk@sheffield.ac.uk email address is going away...

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1419]
From 16 February, service users can use the following support channels:

* IT Self-service portal
* Telephone
* Online chat
* Face-to-face - TechBar

**Comment by jkwmoore** [comment]
Or our direct ingest to Topdesk email. research-it@sheffield.ac.uk

**Comment by jkwmoore** [comment]
This is also partially addressed with this section https://docs.hpc.shef.ac.uk/en/latest/help.html.
