### ISSUE TITLE
Singularity local installtion instructions are out of date

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#1420]
The `Installing Singularity on Your Local Machine` sections of the [Bessemer](https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/singularity.html#installing-singularity-on-your-local-machine) and [ShARC](https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/singularity.html#installing-singularity-on-your-local-machine) are out of date, with recent singularity versions requiring `go` and some other dependency changes.

For the latest installation instructions from singularity see: https://github.com/apptainer/singularity/blob/master/INSTALL.md

It may be worth considering linking to the syslabs fork of singularity instead of the current source repository which is now in the aptainer org, given the upcoming change to apptainer? 

https://github.com/sylabs/singularity/blob/master/INSTALL.md

**Comment by willfurnass** [comment]
I'm looking at migrating our HPCs to Apptainer rather than Singularity for the Linux Foundation support + availability of RPMs from EPEL.

**Comment by willfurnass** [comment]
Should be addressed via https://github.com/rcgsheffield/sheffield_hpc/pull/1466 (will only be merged once Apptainer installed)
