### ISSUE TITLE
qsub: Unknown option

### ISSUE THREAD

**Issue by Mattias421** [rcgsheffield/sheffield_hpc#1445]
Hello there,

A few days ago I could use the qsub command perfectly but today the qsub command returns "qsub: Unknown option". 

Is there anyway I can bring this back to normal?

Thank you,
Matt

**Comment by jkwmoore** [comment]
Please submit a support request via the topdesk. That aside we have not made any changes to the clusters of this nature. The reported error suggests you are running the command incorrectly or have somehow corrupted your environment.

If you are attempting to use qsub on Bessemer, we do not support this as the SLURM scheduler should have jobs submitted with the sbatch command (to avoid potential qsub reparsing / conversion errors.)

**Comment by jkwmoore** [comment]
See the following link for topdesk support: https://www.sheffield.ac.uk/nap/service/redirect/helpdesks
