### ISSUE TITLE
JADE 1 has been decommissioned

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#1452]
JADE (1) has now been decommissioned, so the [JADE]](https://docs.hpc.shef.ac.uk/en/latest/other-uk-hpc-resources/jade.html) (1) needs etiher:

1. removing (ideally with a redirect to JADE 2?)
2. Updating to state it's been decomissioned, link to JADE 2 and remove from the TOC? (`:hidden:`?)

Which option would be preffered?

**Comment by jkwmoore** [comment]
Going to have a look at this now. Probably going to do a stub page mentioning this is no longer available with a meta refresh / explanation and redirection to JADE II. Will link the PR in a bit.

**Comment by jkwmoore** [comment]
Let me know if you'd like some updates to the JADE II page and I can look at sorting something out. (Let me know the shape / form of these.)

Cheers!

**Comment by ptheywood** [comment]
Myself and/or @twinkarma will be submitting some changes to the JADE2/Bede pages about support mechanisms soon after some recent meetings about this so I'll see if there are other changes required when doing that.
