### ISSUE TITLE
Request for multiqc module

### ISSUE THREAD

**Issue by markdunning** [rcgsheffield/sheffield_hpc#1457]
Hi,

Could I please request a module for the multiqc tool?

https://multiqc.info/

This is a multi-purpose tool for aggregating QC reports from a variety of Bioinformatics tools (some of which are already available as modules.

Thanks

**Comment by jkwmoore** [comment]
As this particular package appears to be available from the PyPI repo the best way of sorting out installations is to do so with Anaconda which is already on system on a per user basis.

Please see:

- https://pypi.org/project/multiqc/
- https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/python.html
- https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/python.html

The Python pages will detail the process for creating and using Anaconda / python environments which you can then install this software into with (example on ShARC):

```
qrshx
module load apps/python/anaconda3-4.2.0
conda create -n mybioenvironment python=3.7
source activate mybioenvironment
pip install multiqc
```

I'll close this ticket as we don't process install requests via this repository but feel free to reply in the comments if installing as described above isn't working. (Tested as fine for me.)
