### ISSUE TITLE
R 4.2.1 request

### ISSUE THREAD

**Issue by OLaing1** [rcgsheffield/sheffield_hpc#1521]
Hello, 

I need to use the "DiffBind" package in R for some bioinformatics analysis on ShARC, but the installation is failing, which I believe is due to the available R version being too old (apps/R/4.0.3/gcc-8.2.0). 

Could you install the latest version of R ( R4.2.1) to Sharc?

Best wishes, 

Owen

**Comment by jkwmoore** [comment]
Sorry, this is the documentation website and we cannot do support for users we do not know are TUoS users.

 Please file a ticket on via the University support desk (https://www.sheffield.ac.uk/nap/service/redirect/helpdesks - click "Report a new issue") with this query with some more details:

- Which bioinformatics package you are trying to install?
- What if any 3rd party libraries are required for this package.
- A copy of the terminal commands you have used to attempt the installation.
- A copy of the terminal output from the commands you used to attempt the installation.

If you ask that the ticket is forwarded to Research IT it will ensure it reaches us ASAP.

Note: I am closing this issue on Github, please do not re-open it or detail any sensitive info about your work or workflow publicly - please only do so via the support ticket.
