### ISSUE TITLE
Request for nextflow module

### ISSUE THREAD

**Issue by markdunning** [rcgsheffield/sheffield_hpc#1553]
Hi,

Our group is hoping to promote the use of the nextflow workflow manager for the running of reproducible pipelines on HPC (particularly for Bioinformatics). Could we request a module for nextflow on sharc / bessemer please?

https://www.nextflow.io/

Our particular use-case is that we would like researchers to be using the best-practice and re-usable nextflow pipelines available through nf-core (https://nf-co.re/) rather than cobbling together their own shell scripts

Mark

**Comment by willfurnass** [comment]
Hi @markdunning.  Good idea. I'll create a ticket in our helpdesk system for tracking this as we currently prefer using that for new software installations.

**Comment by Carldkennedy** [comment]
Closing this issue since Nextflow has been installed.

**Comment by Carldkennedy** [comment]
- [ ] Testing
- [ ] Docs
