### ISSUE TITLE
Bowtie2 examples required

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#157]
It would be nice to have some examples of using Bowtie2 in batch mode. The current documentation is a little sparse http://rcg.group.shef.ac.uk/iceberg/software/apps/bowtie2.html

Also, a benchmark that takes a while (no more than a day) which we could use to demonstrate multithreading mode and try out different compiler switches at build time.

Hopefully such examples can be provided that aren't too large?

Perhaps the bioinfomatics community can help us out?

**Comment by souravsingh** [comment]
I have a bit of background in bioinformatics. I would like to help in this

**Comment by mikecroucher** [comment]
Not going to happen and no one seems to care. Closing
