### ISSUE TITLE
Replace references to ReadTheDocs with GitHub Pages

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1600]
Especially in the README.

**Comment by Carldkennedy** [comment]
`grep -ri --exclude-dir=html --exclude-dir=.tox --exclude-dir='_build' 'readthedocs' . | grep -Ev 'readthedocs\.(io|org)'`

Didn't give any results. has this already been done @jkwmoore

**Comment by jkwmoore** [comment]
Can only assume the PR to close this never got linked. Closing.
