### ISSUE TITLE
Add VSCode to FAQ

### ISSUE THREAD

**Issue by Carldkennedy** [rcgsheffield/sheffield_hpc#1601]
If using VSCode for anything more than simply editing scripts on the HPC you are likely to run into issues with spawning many processes on the login node. 

A quick internet search for "vscode spawning processes login node hpc" shows how users of HPC often have these issues. This includes the use of any extensions which will run on the login node (even though you may be logged into a worker node in the vscode terminal).

We have a github repository [vscoderemote_sheffield_hpc](https://github.com/rcgsheffield/vscoderemote_sheffield_hpc) .The purpose of this repository and the two start_vscode.sh scripts is to enable you to run VSCode Remote safely on a worker node using the Sheffield University HPC clusters.

**Comment by jkwmoore** [comment]
See also: SHEF 2301 0208

For more in depth as to why.
