### ISSUE TITLE
MATLAB install notes required

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#17]
There are no installation notes for MATLAB available. I understand that a basic install is straightforward but integration with the SGE is rather more tricky. How was it done for the current installs?

**Comment by cs1ds** [comment]
When I install 2016a on iceberg, which should not be long now, I shall document this.

**Comment by mikecroucher** [comment]
Thanks Deniz :)

**Comment by willfurnass** [comment]
See #384 ; parallel MATLAB setup instructions to follow (need help from @cs1ds for this).

**Comment by mikecroucher** [comment]
How are we doing with this?

**Comment by willfurnass** [comment]
Iceberg decomissioned; closing.
