### ISSUE TITLE
Update ANSYS Multi-core license restrictions

### ISSUE THREAD

**Issue by Carldkennedy** [rcgsheffield/sheffield_hpc#1784]
As of May 10th at 13:00 each ANSYS user will be restricted on a per username basis to using a maximum of 400 cores concurrently. (Out of a maximum of 4500.) 
This limit applies to individual usernames, on any device campus wide. i.e. if they are using 20 licences on their personal machine and 100 on the HPC, this would count as 120 / 400.
This restriction is applied only to the ANSYS multi-core licenses which are held on the research licence server only. (There are no restrictions on the number of ANSYS applications that can be opened by anyone however.)
ANSYS Multi-core licenses are checked out by any ANSYS application, per application, where more than 4 cores are used concurrently, equal to the number of cores in use above 4.
Users who require access to more than 4 cores must use the ANSYS research licence server. (This is not a change from the current status quo, I just wanted to highlight this also.)

**Comment by jkwmoore** [comment]
We probably don't need the warnings to be this verbose, but it should be in short form on each ANSYS or ANSYS derivative page.

**Comment by Carldkennedy** [comment]
Ah just realised I used VASP as an example. Since a licence is needed to use this module would it be better to use another example? Just in case they want to run through it themselves @jkwmoore
