### ISSUE TITLE
Getting Started: Web interface

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#18]
The old docs are at https://www.shef.ac.uk/wrgrid/using/access/browser

Given that this no longer works on Chrome, are we still going to support it?
If so, the docs need writing.

**Comment by cs1ds** [comment]
I have just tested this. It does not work with Chrome whatever you do. I am happy to abandon Chrome method of SGD access and update documentation accordingly.

**Comment by mikecroucher** [comment]
Moribund access method. Closing
