### ISSUE TITLE
Add fingerprints

### ISSUE THREAD

**Issue by Carldkennedy** [rcgsheffield/sheffield_hpc#1803]
https://docs.hpc.shef.ac.uk/en/latest/FAQs.html#login-node-rsa-ecdsa-ed25519-fingerprints needs updating
Update the connecting with SSH page as well as the FAQ to include these for each cluster

**Comment by jkwmoore** [comment]
Tracking in (better titled) https://github.com/rcgsheffield/sheffield_hpc/issues/1814
