### ISSUE TITLE
GULP install

### ISSUE THREAD

**Issue by mt1cmh** [rcgsheffield/sheffield_hpc#191]
Hi,

I have tried to compile GULP on Iceberg, but with no success. Ideally it would be very useful to have this program available for the students in Materials Science and Engineer (plus perhaps those users in Chemistry and Physics).

https://nanochemistry.curtin.edu.au/gulp/

Thanks,

Chris

**Comment by Cadair** [comment]
You have to register to download  the software and the conditions at the bottom of the registration page say:

```
The program GULP is available free of charge to academics provided you accept the following conditions of use:

    The program is not to be distributed to anyone else without the express permission of the author.
    The program is not to be used for commercial research. For any commercial use of the program a license must be obtained from Accelrys Inc, including contract research.
    The program is supplied on an "as is" basis with no implied guarantee or support.
```
the 
```
The program is not to be distributed to anyone else without the express permission of the author.
```
line worries me as that is what we would be doing by installing it on the shared cluster.

@mikecroucher opinions?

**Comment by mikecroucher** [comment]
We should get permission from the author to install here.

**Comment by willfurnass** [comment]
Me to GULP's authors:

> The licensing terms for the GULP software state that the "program is not to be distributed to anyone else without the express permission of the author."  Would you permit us to install your software on our HPC clusters so that it could be accessed by all users of the clusters?  We would ensure that [our documentation](http://docs.hpc.shef.ac.uk) on GULP included the wording "The program is not to be used for commercial research. For any commercial use of the program a license must be obtained from Accelrys Inc, including contract research." as per [your license text](https://nanochemistry.curtin.edu.au/gulp/register.cfm).

Authors' response to me:

> Happy for you to centrally install Gulp on your cluster provided that no industry based users (if you have any) can access the code as per the Accelrys/Biovia condition.

**Comment by mt1cmh** [comment]
Excellent

**Comment by willfurnass** [comment]
@mt1cmh : GULP 4.4 is now installed, tested and documented on ShARC:

http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/gulp.html
