### ISSUE TITLE
Listings in (new Google Custom Search Engine) search results not clickable

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1986]
On Chrome with no plug-ins enabled.

**Comment by jkwmoore** [comment]
Not sure I can replicate? (Chromium on Ubuntu 22.04). Which part are you clicking?

![image](https://github.com/rcgsheffield/sheffield_hpc/assets/69149348/9cd61ffd-e326-429d-b49c-7f13aae67f7c)

Green is the link and clickable, red is not a link (which is odd.)

**Comment by willfurnass** [comment]
Ah, you're right.  Not intuitive what is and isn't a link in those results.

**Comment by willfurnass** [comment]
Can we do something with CSS to help?

**Comment by willfurnass** [comment]
@jkwmoore tweaked the search CSS somehow; problem addressed and links now clearly identifiable.

**Comment by jkwmoore** [comment]
Tweaked via the style settings in the custom search engine (no longer monochrome).
 
![image](https://github.com/rcgsheffield/sheffield_hpc/assets/69149348/8f879fd5-0b1b-4010-8e13-558f3bfb3505)
