### ISSUE TITLE
Stanage GPU request docs have different arguments for interactive jobs vs batch jobs

### ISSUE THREAD

**Issue by fredsonnenwald** [rcgsheffield/sheffield_hpc#2022]
https://docs.hpc.shef.ac.uk/en/latest/stanage/GPUComputingStanage.html#gsc.tab=0

`srun --partition=gpu-h100 --qos=gpu --gres=gpu:h100:1 --pty bash`

vs

```
#!/bin/bash
#SBATCH --partition=gpu-h100
#SBATCH --qos=gpu
#SBATCH --gres=gpu:2
#SBATCH --mem=82G

# Your code below...
```

As near as I can tell interactive jobs work just the same without specifying `gpu:h100:1` and instead just specifying `gpu:1`. Suggest we bring these into parity and let the partition control GPU type exclusively, making it one less thing for users to remember/copy-paste/get wrong.

**Comment by willfurnass** [comment]
Agree that we should use partitions to select/differentiate GPU node types.  (contextual info: we previously thought we'd have both types of GPU node in one partition, but decided against that as it wouldn't allow us to have different `MaxTRESPerUser` thresholds per GPU type).
