### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#212]
The binary install of Tensorflow ( https://www.tensorflow.org ) (A python package, installed via pip) fails with a GLIBC error

In Python, if you do

```
import tensorflow

ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by     /home/fe4test/.local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)
```

So, I looked into installing Tensorflow from source. The source install requires bazel http://bazel.io/contributing.html

Bazel is distributed via binary file. The installer for this fails

```
Uncompressing......./usr/local/packages6/apps/gcc/5.2/bazel/0.1.2/bin/bazel: /lib64/libc.so.6: version     `GLIBC_2.14' not found (required by /usr/local/packages6/apps/gcc/5.2/bazel/0.1.2/bin/bazel)
```

So, I need to compile Bazel from source. The current install script looks like this:

```
#!/bin/bash

module load compilers/gcc/5.2
module load apps/gcc/5.2/git/2.5
git clone https://github.com/bazelbuild/bazel.git
cd ./bazel
./compile.sh
```

This gives the following output

```
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch
```

Then it does nothing. Purging all modules (thus dropping down to system gcc 4.4.7) doesn't change the situation. It just fails silently.

It seems that we are not the first HPC site to have this problem. A user from stanford appears to have similar pain.

https://github.com/bazelbuild/bazel/issues/50

His bazel builds get further than mine, however. At least they appear to start before giving up.

**Comment by willfurnass** [comment]
Should be able to install TensorFlow on ShARC as Centos 7 comes with a sufficiently recent GLIBC:
```
[will@sharc-node005 ~]$ ldd --version
ldd (GNU libc) 2.17
```

**Comment by willfurnass** [comment]
Installed on ShARC: http://docs.hpc.shef.ac.uk/en/latest/parallel/gpu/Tensorflow.html
Closing.
