### ISSUE TITLE
Conda Environment in fastdata area improvement 

### ISSUE THREAD

**Issue by beckywilks** [rcgsheffield/sheffield_hpc#2134]
I received a TopDesk ticket of someone struggling to follow the FAQ added in #2130

1) Change directory paths for Stanage 
2) Add a section about making a fastdata area with correct permissions

**Comment by jkwmoore** [comment]
![image](https://github.com/rcgsheffield/sheffield_hpc/assets/69149348/acd37f2c-731f-4ea9-b06c-9355e59e4d7c)
 Given the above, we're using the `$USER` variable but I don't know if conda will understand and expand that variable (probably not) or whether users need to be explicitly told to swap it out for their username.
