### ISSUE TITLE
Install Spark

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/sheffield_hpc#254]
http://spark.apache.org/

**Comment by anthonybrookfield** [comment]
> I'm not aware of anyone running Spark on Iceberg.  We've had a couple of enquires about it, but no definite use cases yet.  I think it would be possible to get it working with SGE, although I'm not sure if they would make comfortable bedfellows.  Intel have developed a hadoop adapter for lustre, which might make lustre more suitable for Spark, but it's not something we've have much time to investigate.
> 
> Data-centric workloads which aren't well served by traditional HPC setups are certainly an area we're interested in exploring/developing.... 
>

**Comment by mikecroucher** [comment]
I need to do this for Computer Science. Assigning to me.

**Comment by mikecroucher** [comment]
This has been done on Iceberg although only works for workloads that work on a single node at the moment. http://docs.iceberg.shef.ac.uk/en/latest/iceberg/software/apps/spark.html

**Comment by mikecroucher** [comment]
Done and has been used by CS for a semester
