### ISSUE TITLE
VASP installation

### ISSUE THREAD

**Issue by ChrisHandley** [rcgsheffield/sheffield_hpc#261]
Hi,

Can I request VASP to be installed on Iceberg?

Again, I believe it is a case of a program that will need ring fencing, and so VASP has a user list attached to Prof John Harding in Materials Science, for whom fall under.

Thanks,

Chris

**Comment by mikecroucher** [comment]
Hi

Got a link please?

Cheers,
Mike

**Comment by mt1cmh** [comment]
I believe Colin has a copy c.l.freeman@sheffield.ac.uk .

He should be able to better advise on the license restrictions on how it is
installed.

Thanks,

Chris

On 16 February 2016 at 17:11, Mike Croucher <notifications@github.com>
wrote:

> Hi
>
> Got a link please?
>
> Cheers,
> Mike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/261#issuecomment-184777187>
> .
>



-- 
Dr. Christopher Handley
Dept of Materials Science and Engineering
Sir Robert Hadfield Building
Mappin Street
Sheffield
S1 3JD
UK

**Comment by mikecroucher** [comment]
The license restrictions are the most important.

**Comment by mt1cmh** [comment]
HI Mike,

With the VASP license, it can be installed on any machine, so long as it is
ring fenced to the group.

https://www.vasp.at/index.php/faqs/78-on-how-many-computers-may-vasp-be-installed

https://www.vasp.at/index.php/faqs/71-how-can-i-purchase-a-vasp-license

The license we have is under John Harding's name. I believe that VASP has a
list of users for each research group, however, Colin or John would know
better than I.

https://www.vasp.at/index.php/faqs/72-to-whom-are-vasp-licenses-given

That is as much information I know on the subject, and as much as I can
help as the license information is held by John.

Thanks,

Chris

On 23 March 2016 at 08:53, Mike Croucher <notifications@github.com> wrote:

> The license restrictions are the most important.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/261#issuecomment-200253703>
>



-- 
Dr. Christopher Handley
Dept of Materials Science and Engineering
Sir Robert Hadfield Building
Mappin Street
Sheffield
S1 3JD
UK

**Comment by mt1cmh** [comment]
Hi Mike,

I am just following up this request.

I will also open a ticket regarding the installation of Quantum Espresso,
once I have all the license information for you.

Thanks,

Chris

On 29 March 2016 at 10:01, Christopher Handley <c.m.handley@sheffield.ac.uk>
wrote:

> HI Mike,
>
> With the VASP license, it can be installed on any machine, so long as it
> is ring fenced to the group.
>
>
> https://www.vasp.at/index.php/faqs/78-on-how-many-computers-may-vasp-be-installed
>
> https://www.vasp.at/index.php/faqs/71-how-can-i-purchase-a-vasp-license
>
> The license we have is under John Harding's name. I believe that VASP has
> a list of users for each research group, however, Colin or John would know
> better than I.
>
> https://www.vasp.at/index.php/faqs/72-to-whom-are-vasp-licenses-given
>
> That is as much information I know on the subject, and as much as I can
> help as the license information is held by John.
>
> Thanks,
>
> Chris
>
> On 23 March 2016 at 08:53, Mike Croucher <notifications@github.com> wrote:
>
>> The license restrictions are the most important.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rcgsheffield/iceberg_software/issues/261#issuecomment-200253703>
>>
>
>
>
> --
> Dr. Christopher Handley
> Dept of Materials Science and Engineering
> Sir Robert Hadfield Building
> Mappin Street
> Sheffield
> S1 3JD
> UK
>



-- 
Dr. Christopher Handley
Dept of Materials Science and Engineering
Sir Robert Hadfield Building
Mappin Street
Sheffield
S1 3JD
UK

**Comment by mt1cmh** [comment]
Just bumping this request as we are expecting to have new users in the coming month and will be getting a second license to cover those users. Thanks.

**Comment by mikecroucher** [comment]
Hi Chris

I'm not going to be able to install this any time soon I'm afraid. 
I'll see if the CiCS Research Support Group has any spare capacity.

**Comment by cs1ds** [comment]
I had a brief look at this.  We need passwords for web downloads of the software.
I guess Colin or John Harding would have been given a password.

**Comment by cs1ds** [comment]
Norbert is now working on this

**Comment by mt1cmh** [comment]
Is there any update on the installation, as I am now looking to using this program for a number of projects.

**Comment by mt1cmh** [comment]
Hi, since September I have no been trained on the use of VASP and would like to run some test calculations on Iceberg. Has the installation been tested and is there an example script for how it should be called and the call for when running VASP in parallel and on gpus?

**Comment by willfurnass** [comment]
As discussed, I'm going to investigate,

**Comment by willfurnass** [comment]
[On ShARC](https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/vasp.html); closing.
