### ISSUE TITLE
Gromacs 1.5.2 install on Iceberg

### ISSUE THREAD

**Issue by anthonybrookfield** [rcgsheffield/sheffield_hpc#264]
Request for Gromacs 1.5.2 update (with GPU acceleration?) from David Swainsbury (via Helpdesk).

> Hi,
> 
> Gromacs version 5.1.2 has recently been released with a lot of important
> bug fixes over 5.1.0. A few of these are essential to the work I am trying
> to do.
> 
> Link to the software page here http://www.gromacs.org/
> 
> Would it be possible to update to this version? Also could we try it with
> GPU acceleration?
> 
> Many thanks
> 
> Dave

**Comment by mikecroucher** [comment]
This could resolve #132 as well :)

**Comment by willfurnass** [comment]
New-ish versions of GROMACS w/ GPU support on ShARC (https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/gromacs.html); closing
