### ISSUE TITLE
Install Taverna CLI on Iceberg and ShARC and create usage docs

### ISSUE THREAD

**Issue by gtfletcher** [rcgsheffield/sheffield_hpc#329]
For some of the computational research services within MultiSim, Taverna is required to manage pre-programmed analysis workflows. 

Can we please install the software on the iceberg module system? 

Cheers, Gareth.

**Comment by willfurnass** [comment]
Taverna now appears to be installed on Iceberg in `/usr/local/extras/taverna/` and can be activated using
```
module load apps/binapps/taverna/cli/2.5.0
```

However, there is presently no documentation on `https://docs.hpc.shef.ac.uk`

**Comment by willfurnass** [comment]
* Taverna on ShARC: http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/taverna-cli.html
* Not going to create modulefile for Iceberg.
