### ISSUE TITLE
SGE accounting docs

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#33]
Documentation concerning some of the SGE accounting mechanism would be useful. Here's a random collection of facts:

qacct -j [jobid] 

...you may end up with multiple jobs matching because our JobIDs have wrapped around.

The accounting file is at /usr/local/sge/live/default/accounting.
Records look like this

interactive.q:testnode03.iceberg.shef.ac.uk:fe:fe1abc:INTERACTIVE:26833:sge:0:1433190433:1433190450:1433190450:0:1:0:0.003999:0.001999:1612.000000:0:0:0:0:710:0:0:16.000000:8:0:0:0:11:3:SHEFFIELD:defaultdepartment:NONE:1:0:0.005998:0.000000:0.000000:-U cstest -u fe1mpc -l h_vmem=16G -I y -P SHEFFIELD:0.000000:NONE:0.000000:0:0

See man accounting for the fields.

Apparently this info also ends up on our splunk server. What's that? Where is it? How does it end up there? How can it be used. So many questions.....

**Comment by Cadair** [comment]
The splunk stuff is for cics users only.

**Comment by willfurnass** [comment]
Also need to note that users need to be patient when running `qacct` (at least until we set up log rotation).

**Comment by willfurnass** [comment]
Log rotation now set up.  Need to make people aware of how can query previous accounting files in `$SGE_ROOT/default/common/accounting-archive/` using e.g.

```
qacct -f $SGE_ROOT/default/common/accounting-archive/accounting-20170601
```

(NB we could at some point write a wrapper around the above that trawls all available archives or all archives up to a certain age)

**Comment by willfurnass** [comment]
Closing as ShARC to be decommissioned
