### ISSUE TITLE
Iceberg: update list of processor architectures

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#344]
The list [here](http://docs.iceberg.shef.ac.uk/en/latest/using-iceberg/sge.html#scheduler-options) is incomplete (as is the list in the [documentation outside this repository](https://www.shef.ac.uk/cics/research/hpc/iceberg/specs)).  The full list as of today:

``` bash
$ qhost | awk '{print $2}' | egrep -i '(intel|amd)' | uniq -c | sort -nr
    100 intel-e5-2650
     96 intel-x5650
     11 intel-e5-2670
      8 intel-e5-2670
      7 amd-2376
      4 intel-x5650
      4 intel-e5-2660
      3 amd-2218he
      2 amd-6176
      2 amd-6136
      2 amd-2218he
      1 amd-6380
      1 amd-6328
      1 amd-2376
      1 amd-2218he
```

Also need to add a brief note on _why_ this is could be important.

**Comment by Cadair** [comment]
some of those might not be in the public queue tho right?

**Comment by willfurnass** [comment]
Iceberg decomissioned; closing.
