### ISSUE TITLE
SGE can/will allocate to variety of processors unless explicitly told to use a certain CPU arch

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#345]
Programs optimised for a certain CPU architecture e.g. Intel Westlake may fail on certain nodes with 'Illegal Instruction' errors if run on Iceberg without specifying a target CPU archtecture using `-l arch` in the job spec.  

Need to 
- Note the importance of specifying architecture if running multi-node job using optimised code.
- Make a note in troubleshooting section on significance of 'illegal instruction' error

**Comment by mikecroucher** [comment]
Should also be mentioned on any applications that have made use of optimisation. 

I've done it for the Intel build of R 

http://docs.iceberg.shef.ac.uk/en/latest/software/apps/intel_r.html

**Comment by willfurnass** [comment]
Added notes to troubleshooting section (#525).
