### ISSUE TITLE
Add info on running GPU visualisation jobs using qsh-vis

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#355]
Not an official SGE utility but would be good to document [here](http://docs.iceberg.shef.ac.uk/en/latest/software/scheduler/index.html) all the same.

**Comment by willfurnass** [comment]
Other info:

The easiest option to create an interactive GPU visualisation session is the via the [https://myapps.shef.ac.uk](https://myapps.shef.ac.uk) portal.

Notes on the setup: [http://solarwavetheory.blogspot.co.uk/2015/05/remote-visualisation-guide-and-example.html](http://solarwavetheory.blogspot.co.uk/2015/05/remote-visualisation-guide-and-example.html)

PDF on the University CMS: [https://www.shef.ac.uk/polopoly_fs/1.417678!/file/remote-visualization.pdf](https://www.shef.ac.uk/polopoly_fs/1.417678!/file/remote-visualization.pdf) (up to date?)

**Comment by Cadair** [comment]
I would rather we not recommend people use the myapps portal... but this needs doing.

**Comment by willfurnass** [comment]
@Cadair why?

**Comment by Cadair** [comment]
Because it involves faffing around with the plugin and I don't like it. Personal preference though.

**Comment by willfurnass** [comment]
Neither do I.  On Ubuntu I needed to install manually (once I'd found the download URL), check dependencies using `ldd` then install several 32-bit X-related libs to get it working.  Others seem to use and like it though.

**Comment by willfurnass** [comment]
Closing as ShARC to be decommissioned
