### ISSUE TITLE
Link checking

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#375]
Would be good to incorporate internal link checking within our continuous integration config and/or automate regular internal and external link checking using an external service or something like [Broken Link Checker](https://www.npmjs.com/package/broken-link-checker) + cron.

Having Sphinx itself check internal links during a build would help; however, at present things like scripts and modulefiles aren't copied to the `_build_html` output directory so all links to such things are (and have to be) absolute URLS pointing at files on GitHub. Would it be better to copy these scripts to the output directories during the build process then ensure every URL that can be internal to the repo is, using URLs that are absolute or relative to the web root?

@Cadair : any thoughts on this?

**Comment by willfurnass** [comment]
Looks like we can use Sphinx's [:download:](http://www.sphinx-doc.org/en/1.4.8/markup/inline.html#role-download) role in our reStructuredText files for internal links to non-reStructuredText files e.g. shell scripts, modulefiles.  An example:

```
See :download:`this example script </sharc/software/install_scripts/apps/java/jdk1.8.0_102/binary/install.sh>`.
See :download:`this example script </sharc/software/install_scripts/dev/NAG/install_NAG_compiler_6.1.sh>`.
```

results in files (but not dirs) being copied to the `_downloads` output subdirectory (NB duplicate filenames handled) and relative links inserted into the output HTML.

A nice effect of doing things this way is that Sphinx will error at build time if files referenced by the `:download:` role don't exist.

**Comment by Cadair** [comment]
This sounds like an excellent solution.

**Comment by willfurnass** [comment]
Closing; need to add notes to this in documentation on how to contribute (#454)
