### ISSUE TITLE
Install FLAME GPU cluster-wide

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#401]
@mondus @mikecroucher Following on from #397 we should install a specific build of FLAME GPU cluster-wide, complete with a modulefile.  

@mondus Does FLAME_GPU require that `CUDA_ROOT` is set?  If so, we can set it to the value of `CUDA_HOME` in the modulefile for FLAME GPU (with `CUDA_HOME` already being set by the _CUDA_ modulefile to something like `/usr/local/packages6/libs/binlibs/CUDA/7.5.18/cuda/`).

**Comment by mondus** [comment]
There is currently not a release of FLAME GPU with linux support (only the main development branch). Once we make a release then we can do a module file.

FLAME GPU only requires that a `CUDA_PATH` environment variable is set. This can be set from `CUDA_HOME` by default but is changeable for systems with multiple CUDA versions where `CUDA_HOME` is set to the latest version.
