### ISSUE TITLE
Intel Suite issues on ShARC

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#410]
The Intel compiler and the various libraries are not documented on the ShARC website.
There are also problems with how the module files are presented.  We have, for example, 

`libs/intel-tbb/2017/binary`

I can see why this was done -- the Intel-tbb came from the 2017 distribution of the compiler suite. However, there will be lots of releases of compilers, MKL, tbb etc throughout the 2017 cycle and version numbers will increment out of step of each other.  

For the compiler, I recommend we change to 

`dev/intel-compilers/17.0.0`

Note that I have dropped `binary`. We usually don't care how compilers were compiled.
What matters is how libraries and apps were compiled.

**Comment by willfurnass** [comment]
@mikecroucher How are new versions of components of Parallel Studio typically made available?   

My current plan is to install PS 2017.0 into `/usr/local/packages/dev/intel-ps-xe-ce/2017.0` then create the following modulefiles:

* `libs/intel-daal/2017.0/binary`
* `libs/intel-ipp/2017.0/binary`
* `libs/intel-mkl/2017.0/binary`
* `libs/intel-tbb/2017.0/binary`
* `dev/intel-compilers/17.0.0`

Does this look sensible?

**Comment by mikecroucher** [comment]
In the past, we've just had one module for all of it.

E.g. `module load dev/intel-compilers/17.0.0` would load daal, ipp, mkl and tbb.  
If you wanted *just* MKL but not the compiler (say), we had nothing for you.

Your separation makes sense but....

* It makes much more work for us 
* No one has ever asked for it.
* I've never encountered a problem that needs it.

I'm not saying that we shouldn't separate the modules. It's nice and clean after all....but is it worth the extra effort?

**Comment by willfurnass** [comment]
What if to use a give application a user needs a particular version of libstdc++ (provided by GCC),  wants the MKL and also wants to use CUDA (requires GCC<=5)?  Which modules to activate and in which order?

Best if libraries/compilers that do very different things are provided by different modules.

**Comment by mikecroucher** [comment]
true. More work it is then :)

**Comment by willfurnass** [comment]
Closing; feel free to re-open if necessary.
