### ISSUE TITLE
NAG library on iceberg is a bit of a mess at the moment.

### ISSUE THREAD

**Issue by cs1ds** [rcgsheffield/sheffield_hpc#416]
I noticed that a lot of the older NAG libraries are no longer working on iceberg and the whole thing needs a revamp.   I don't think the licenses are updated for the PGI compilers. I shall have a look at these issues and also remove some of the older scripts in /usr/local/bin such as the family of (nagexample* ) scripts as well as the documentation that is no longer accurate.

**Comment by mikecroucher** [comment]
The revamp has happened. It is here

http://docs.iceberg.shef.ac.uk/en/latest/iceberg/software/libs/nagfortran.html

None of the other stuff was documented so I ditched it. No one complained!
Hence, we probably don't need to do anything else here.

**Comment by cs1ds** [comment]
The KUSARI KEYS have arrived for the NAG Fortran PGI and GNU Libraries
FLL6A24DFL, FLL6A24DPL and FLL6A23DHL 
and I have added them onto the NAG library license keys file 
(i.e. /usr/local/packages5/nag/license.lic ) .

**Comment by mikecroucher** [comment]
I think this is resolved now. closing
