### ISSUE TITLE
Iceberg + NAG libraries : remove legacy symlinks and env vars

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#426]
@cs1ds Now that we are using environment modules for activating the NAG libraries and compiler can we remove the following?

 * `NAG_KUSARI_FILE=/usr/local/packages5/nag/license.lic` from `/etc/profile.d/shef-login.sh:export`?
 * `nag*` from `/usr/local/bin/`?
 * `/usr/local/modulefiles/libs/nag/24`

then notify users that we've done so?

**Comment by mikecroucher** [comment]
looks good to me.

**Comment by cs1ds** [comment]
I have started tidying these up now.

**Comment by mikecroucher** [comment]
@cs1ds How are we doing with this issue?

**Comment by willfurnass** [comment]
Iceberg decomissioned; closing.
