### ISSUE TITLE
ReadTheDocs not automatically updating following push to master branch

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#432]
Can one of the owners of https://readthedocs.org/projects/iceberg (@Cadair @mikecroucher @anthonybrookfield ) add me as an owner so I can check the config?

**Comment by anthonybrookfield** [comment]
I think that should be done.  I've also removed @cadair.

**Comment by willfurnass** [comment]
Working again.  May have been due to readthedocs using the old repo name and not liking the github redirect to the new repo name.  Closing.
