### ISSUE TITLE
Install PGI compiler on ShARC

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#441]
@mikeg64 @cs1ds Which product on http://www.pgroup.com/support/download_pgi2016.php?view=current do we need to download and install?

**Comment by cs1ds** [comment]
Mike C. had installed the latest version of the PGI compilers on iceberg ( 15.10 )  although the default is still 15.7 that was installed by me.  I would guess it would be appropriate to keep the default versions the same on both iceberg and sharc ( to start the service with anyway ) .  
I have already suggested that we make 15.10 the default version on iceberg on an earlier discussion and waiting to hear from Mike C. if that can be done.  So, assuming the answer is yes to that, I would suggest 15.10

**Comment by cs1ds** [comment]
I have just noticed on the PGI site that 15.10 is over a year old. I would suggest we can also download the very latest version only to sharc but not yet make it the default release.

**Comment by willfurnass** [comment]
In answer to my question above, Deniz thinks we need to install *PGI Accellerator C/C++/Fortran Workstation* (version 16.9, updated September 9, 2016)

**Comment by mikecroucher** [comment]
This was done ages ago. 16.10 is currently on ShARC
