### ISSUE TITLE
Fonts problems with qmon and ansys on ubuntu workstations

### ISSUE THREAD

**Issue by cs1ds** [rcgsheffield/sheffield_hpc#456]
If users can not get `qmon` to work at all or get Chinese fonts in dialogs. Doing the following helps:

```
sudo apt-get install xfonts-75dpi xfonts-100dpi   
```

and a reboot ....

This probably fixes many other similar problems when accessing iceberg or sharc from ubuntu

**Comment by willfurnass** [comment]
Good sleuthing!

**Comment by willfurnass** [comment]
Info now in troubleshooting section.
