### ISSUE TITLE
Multiple web addresses leading to the same documentation may be confusing? Also one is outdated

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#467]
The official website according to the repository is supposed to be http://docs.hpc.shef.ac.uk/ but most of my google searches for Iceberg documentation lists the http://docs.iceberg.shef.ac.uk/ domain first. Maybe it would be good to do a permanent redirect rather than mirroring?

The http://rcg.group.shef.ac.uk/iceberg/ domain has the same but outdated documentation (e.g. "Parallel Computing" -> "GPU Computing" -> "FLAME GPU" page does not exist).

The http://rcg.group.shef.ac.uk/icesoftonly/ has the same colour scheme but a totally different layout and similar-ish content.

**Comment by willfurnass** [comment]
The `rcg.group.shef.ac.uk` sites [are hosted on cPanel](https://www.sheffield.ac.uk/cics/cpanel).  Presumably these were set up for testing at some point.  I've asked the cPanel team for info on ownership and asked that we remove/rename the dirs containing the out-of-date docs.

**Comment by willfurnass** [comment]
- [ ] Remove http://rcg.group.shef.ac.uk/iceberg/ draft docs
- [ ] Remove  http://rcg.group.shef.ac.uk/icesoftonly/  draft docs
- [ ] Set up redirect from http://docs.iceberg.shef.ac.uk/ to http://docs.hpc.shef.ac.uk/

**Comment by willfurnass** [comment]
@Cadair know anything about the `rcg` cPanel account?

**Comment by Cadair** [comment]
docs.iceberg and docs.hpc are just DNS CNAMEs to the same content, so they are fine as is.

You should speak to @mikeg64 or @cs1ds about the cPanel account, it should be as simple as sshing in and deleting a couple of directories.

**Comment by Cadair** [comment]
It is possible in sphinx to configure a canonical URL for the documentation so Google always links to the correct URL see http://docs.readthedocs.io/en/latest/canonical.html

**Comment by willfurnass** [comment]
Thanks; canonical URL already set to docs.hpc.shef.ac.uk.  Content hosted on rcg.group.shef.ac.uk cPanel account taken down (thanks @cs1ds).  Asked Google to reindex all relevant URLs using the [Google Search Console](https://www.google.com/webmasters/tools/submit-url).
