### ISSUE TITLE
ShARC: install CUDA-compatible OpenMPI 

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#472]
As requested by @mikeg64 and may be of interest to @mondus and @karmauk.

At present CUDA appears to require GCC < 5.0.  I'm therefore going to install OpenMPI 2.0.1 built using GCC 4.9.4.

NB in future we could experiment with enabling 'support for sending and receiving CUDA device memory directly'.  See the FAQs for [Running CUDA-aware OpenMPI](https://www.open-mpi.org/faq/?category=runcuda) and [Building CUDA-aware OpenMPI](https://www.open-mpi.org/faq/?category=buildcuda).

**Comment by mondus** [comment]
Unless you are using devices across nodes then the correct way to do this is with direct GPU communication. You can use device to device copies (optimal) or let unified memory take care of everything (easy).

**Comment by willfurnass** [comment]
So am I right in saying that saying that enabling OpenMPI 'support for sending and receiving CUDA device memory directly' is not a priority right now?

**Comment by mondus** [comment]
I would say so unless there is a particular application which is dependant on OpenMPI for device to device communication. The Deep Learning packages are good examples of how to properly do device to device comms on a single node (i.e. using explicit memory copies). Given we have up to 8 GPUs devices per node the only reason to have OpenMPI would be if you needed to exceed this. I doubt there are many users who need to do this!

**Comment by fgeorgatos** [comment]
you would probably like to have a look at:
https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/g/goolfc/goolfc-2016.08.eb

Using EasyBuild, you can automatically produce a cuda-aware OpenMPI and much more, in a single strike.

**Comment by willfurnass** [comment]
@fgeorgatos Thanks; EasyBuild (along with Spack) is on my list of things to investigate!
