### ISSUE TITLE
Install mosh  on ShARC

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#481]
Mosh (https://mosh.org/) is an asynchronous mobile shell.  From the site's description:

    Remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

I've had a few users request for this as some people work from laptops or in departments with intermittent internet connection. Seems like a nice thing to have but its definitely something I cannot install myself locally as it needs a server similar to SSH.

**Comment by willfurnass** [comment]
Sounds interesting and useful; I hadn't come across it before.

**Comment by karmauk** [comment]
Me neither but it definitely seems like a great tool to have. Had a quick read about the technical details and it seems the big thing that it can't do is  X forwarding and ssh-agent forwarding. 

No X forwarding might be fine as most applications does not require a GUI but I have no idea bout ssh-agent forwarding.

**Comment by mikecroucher** [comment]
is there anything we need to worry about regarding mosh and interactive worker sessions i.e. `qrsh`?

**Comment by karmauk** [comment]
If I understand correctly, mosh creates an ssh connection/authentication to the server and starts individualised ``mosh-server`` on the head node that allows the user to maintain an asynchronous terminal session. ``qrsh`` etc. should work as normal as it gets run on the session created by mosh. 

I'm definitely not an expert on this so I may be wrong. Also I can't seem to find any documentation/articles on using mosh with the grid engine.

**Comment by karmauk** [comment]
I've managed to build a version of mosh that works on sharc but we need to open up some UDP ports to test it out.  Normal port range is 60000-61000.

**Comment by twinkarma** [comment]
Looks like this will be difficult to integrate in to SGE, will also need to consider the logistics of hanging session.
