### ISSUE TITLE
Installation of Torch on ShARC

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#487]
I'm planning to install Torch (http://torch.ch/) as a module for ShARC. It uses lua scripts to create DL models.

The installer comes in a nice self-contained script that installs all its dependencies locally.

- [x] documentation
- [x] install script
- [x] module script

**Comment by willfurnass** [comment]
@twinkarma Can this be closed?

**Comment by twinkarma** [comment]
Yep all done.
