### ISSUE TITLE
Installation of Caffe on ShARC

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#488]
Caffe (http://caffe.berkeleyvision.org/) is a c++ deep learning library. Its's got quite a few dependencies but Everything can be installed locally and I'm working on an automated install script.

- [x] documentation
- [ ] install script
- [ ] module script

Dependencies :
- [x] cmake (just to build it)
- [x] blas (atlas)
- [x] boost (Can use package in conda)
- [x] opencv
- [x] protof
- [x] glog
- [x] gflags
- [x] hdf5 (Can use package in conda)
- [x] leveldb
- [x] snappy
- [x] lmdb
- [x] caffe

**Comment by willfurnass** [comment]
We should install boost, cmake and hdf5 separately as they will be used for many other purposes.  I can look at these if you like.  Which compiler are you wanting to use?

**Comment by karmauk** [comment]
It'll have to be 4.9.2 because of CUDA 8.0.

**Comment by karmauk** [comment]
Caffe test failed 2 out of 2085 tests. Need to check how important this is.

```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithEverythingShare, where TypeParam = caffe::GPUDevice<float>
[  FAILED  ] NesterovSolverTest/2.TestNesterovLeastSquaresUpdateWithEverything, where TypeParam = caffe::GPUDevice<float>

```

**Comment by willfurnass** [comment]
@twinkarma Is this ticket now redundant given the move to using Singularity?

**Comment by twinkarma** [comment]
I've just finished a new build and it will be the last module as we transition to Singularity. Will be making a pull request of the docs as soon as the NCCL module load issue is sorted.
