### ISSUE TITLE
Add page on how ShARC differs from Iceberg

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#506]
- [ ] the real time limit (`h_rt`) in ShARC's default queue (`all.q`) is only four days but on Iceberg `long.q` has a time limit of seven days.  At present if users submit jobs to ShARC and ask for `h_rt` > four days then these jobs will never be run but no error/warning will be given.
- [x] Modules have different names
- [x] Haswell processors, which allow for fused add & multiply
- [x] `rmem` is used to limit the real memory used; `mem` requests are now ignored by the scheduler.
- [ ] GPUs are to be exclusively reservable
- [ ] Home directories are shared with Iceberg
- [ ] Queue names are shorter / simpler but there are aliases for the old ones.
- [ ] Different Grid Engine 'complex' names (for CPUs and GPUs)
- [x] Access only from campus / over VPN at present.
- [ ] qstat behaviour differs

**Comment by mondus** [comment]
"GPUs are to be exclusively reservable" Is there a plan for how this would work?

**Comment by willfurnass** [comment]
@mondus https://github.com/RSE-Sheffield/sge-gpuprolog/pull/9

**Comment by mikecroucher** [comment]
How about the specs of ShARC? 
We have this for Iceberg. http://docs.hpc.shef.ac.uk/en/latest/iceberg/cluster_specs.html

@anthonybrookfield Are the iceberg specs still correct? What do they look like for ShARC? I'm happy to write the page if I have the stats.

**Comment by mondus** [comment]
Mike G write this summary

https://sites.google.com/a/sheffield.ac.uk/rcg/my-blog/introducingthesheffieldadvancedresearchcomputer

**Comment by willfurnass** [comment]
@mikecroucher The spec is a separate issue (#486)

**Comment by mikecroucher** [comment]
The summary that Mike G wrote is out of date

**Comment by mikecroucher** [comment]
I've started making a dent in this in PR #571 
What I've done is far from perfect but I felt that something was better than nothing can we can iterate on it.

**Comment by mikecroucher** [comment]
@anthonybrookfield are /data and /fastdata shared between systems?

**Comment by willfurnass** [comment]
@mikecroucher /data is shared, /fastdata is not

**Comment by willfurnass** [comment]
Closing as ShARC to be decommissioned
