### ISSUE TITLE
Tip for multiple mpirun cmds in a single batch job

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#524]
If you have multiple mpirun commands in a single batch job submission script then you may find that one or more of these may fail after complaining about not being able to communicate with the `orted` daemon on other nodes.  This appears to be something to do with multiple mpiruns being called quickly in succession, and connections not being pulled down and new connections established quickly enough.

Putting a sleep of e.g. 5s between mpirun commands seems to help here.  

Should mention this in *Troubleshooting*.

Discovered when running the test suite of GULP 4.4 (on ShARC using OpenMPI 2.0.1 built with Intel 17.0.0)

**Comment by mikecroucher** [comment]
Done in https://github.com/rcgsheffield/sheffield_hpc/pull/598
