### ISSUE TITLE
What is ENH_libs ?

### ISSUE THREAD

**Issue by cs1ds** [rcgsheffield/sheffield_hpc#531]
Having last worked with iceberg_software repository,  on my return I did a git pull which reported to my surprise that everything was upto-date !!!
When I did a git status it reported that I was on branch ENH_nag_libs !!!
Can someone tell me what is going on please ?

**Comment by cs1ds** [comment]
I just did a "git pull upstream master" which seemed to update a few things. 

Now it reports that I am still on branch ENH_nag_libs and my branch is ahead of origin/ENH_nag_libs  by 188 commits.  Should I be happy ???

**Comment by willfurnass** [comment]
Sorted.  `cs1ds/ENH_nag_libs` had previously been merged into `upstream/master` so just deleted that feature branch.  

We should add info to the docs on how to use git to make small contributions to the docs (created Issue #532).
