### ISSUE TITLE
SGE_CLUSTER_NAME not set on Sharc

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#533]
On iceberg: 

```
echo $SGE_CLUSTER_NAME
iceberg
```

This is not set on sharc.

This would be useful for, e.g., benchmarking scripts.

@anthonybrookfield or @willfurnass - what do you think?

**Comment by willfurnass** [comment]
+1 for setting it in `/etc/profile.d/SoGE.sh`

**Comment by anthonybrookfield** [comment]
Yeah, @willfurnass has poked me about this before.  I can't think of a reason not to do this (and looking through the $SGE_ROOT configs it looks like it's still a thing, so I'll add it to ShARC.  (I'll also pull in @willfurnass 's DRMAA_LIBRARY_PATH addition.  

(might take a little while to do - I think puppet/foreman hasn't recovered from the Xmas holidays yet....)

**Comment by willfurnass** [comment]
See PR to puppet repo

**Comment by anthonybrookfield** [comment]
applied.

**Comment by willfurnass** [comment]
Done for login and worker nodes:

```
$ env | egrep -e '(DRMAA|SGE_CLUSTER_NAME)'
DRMAA_LIBRARY_PATH=/usr/local/sge/live/lib/lx-amd64/libdrmaa.so
SGE_CLUSTER_NAME=sharc
```
