### ISSUE TITLE
Mathematica 11.0.1 install

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#554]
Requested by Evgeny Chekhovich

**Comment by mikecroucher** [comment]
done on Iceberg.

**Comment by anthonybrookfield** [comment]
Are you planning to do an install on ShARC?  I've recieved a request for a version of mathematica to be installed on ShARC from Kai Zeng.

**Comment by mikecroucher** [comment]
Yes.

**Comment by anthonybrookfield** [comment]
Just been asked again about this...

I could give the install a go based on your install notes from Iceberg... is the 11.0.1 linux media from the sheffield software downloads site (Mathematica_11.0.1_LINUX.sh) the right media to use?

**Comment by willfurnass** [comment]
v12 on ShARC: https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/mathematica.html
