### ISSUE TITLE
An error when I use tensorflow

### ISSUE THREAD

**Issue by Heipiao** [rcgsheffield/sheffield_hpc#585]
tensorflow 0.11
when I run a mnist demo, the log in below:
![capture](https://cloud.githubusercontent.com/assets/9475632/24480475/763e9c84-14dc-11e7-9628-7c7f076d0357.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9475632/24480477/78243ba8-14dc-11e7-8af2-4f62985d1c12.PNG)
the the program is exit, not run.
i see the issue page os tensorflow,[https://github.com/tensorflow/tensorflow/issues/2145](url) said there maybe a wrong config on CUDA

**Comment by willfurnass** [comment]
@karmauk Any thoughts on this?

**Comment by karmauk** [comment]
I've encountered this problem before. It seems that Tensorflow struggles when it finds too many GPUs. Try running with the command which uses just GPU number 0:

```

CUDA_VISIBLE_DEVICES=0 python your_minist_script.py

```

I've also noticed that Tensorflow performance seems to be very poor when training across multiple GPUs, even between with peer access, and I will be looking in to why that is.

**Comment by karmauk** [comment]
The strange thing here is that the standard MNIST code does not have code to train on multiple GPUs. Their Cifar model do have code where you can specify the number of GPUs to use and I think have successfully made it do up to 4 GPUs but very very slowly.

**Comment by Heipiao** [comment]
CUDA_VISIBLE_DEVICES=0 slove the problem. thank you @twinkarma
