### ISSUE TITLE
ShARC: promote qrshx as 'qrsh for humans'

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#594]
From the comment block in https://gist.github.com/willfurnass/10277756070c4f374e6149a281324841:

```
# `qrsh` is often the most convenient utility for starting interactive shell
# sessions on Sun/Son of Grid Engine (SGE) clusters but it has some limitations (as
# configured on the ShARC/Iceberg clusters):
# 
# - none of the standard SGE environment vars (e.g. JOB_ID, PE_HOSTFILE,
#   NSLOTS) that are defined in qsub/qsh batch/interactive sessions are set
#   (annoying but not the end of the world);
# - variables can't be set in prolog scripts (e.g. the CUDA_VISIBLE_DEVICES env
#   var needed for exclusively locking GPUs to jobs);
# - X display forwarding doesn't work.
#
# This script addresses these three issues.  It starts a qrsh shell session in
# which:
#
#  - all environment variables set by the scheduler (e.g. JOB_ID) are set
#  - X display forwarding is enabled if necessary
```

- [x] Set up on ShARC
- [x] Determine why it doesn't work reliably in conjunction with `-P rse` and `-l gpu=` (which causes the [GPU-locking prolog script](https://github.com/RSE-Sheffield/sge-gpuprolog/) to be run) unless used with `-now n` (see [my query on the sge-discuss mailing list](http://arc.liv.ac.uk/pipermail/sge-discuss/2017-April/001127.html)) - it seems as though the delay induced by the prolog script causes a timeout to be hit.
- [x] Promote in the docs inc describe usage on  http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/qrshx.html

**Comment by mikecroucher** [comment]
Also need to update http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/qrshx.html

**Comment by willfurnass** [comment]
And ensure that qrshx is updated on iceberg to match ShARC.

**Comment by willfurnass** [comment]
@anthonybrookfield Can you set up the revised `qrshx` on iceberg?
