### ISSUE TITLE
Can't get mercurial running

### ISSUE THREAD

**Issue by leondz** [rcgsheffield/sheffield_hpc#595]
Hi,

I can't get Mercurial running in any kind of environment on Sharc; I've tried installing through conda, installing through pip, and installing from source. All these fail. Can anyone point me to how to get this VCS running?

@twinkarma

**Comment by twinkarma** [comment]
@willfurnass any ideas?

**Comment by willfurnass** [comment]
The following works for me:

```
will@mysofa ~ $ ssh sharc

[te1st@sharc-login1 ~]$ qrshx
[te1st@sharc-node001 ~]$ module load apps/python/conda
[te1st@sharc-node001 ~]$ conda create -n mercurial_test python=2.7 mercurial
...
[te1st@sharc-node001 ~]$ source activate mercurial_test
(mercurial_test) [te1st@sharc-node001 ~]$ hg clone http://www.selenic.com/repo/hello my-hello
...
(mercurial_test) [te1st@sharc-node001 ~]$ ls -a my-hello/
.  ..  hello.c  .hg  Makefile
```

Alternatively, if you don't need a particularly recent version of Mercurial then we could install the the operating system (Centos 7.x) package for Mercurial, which currently provides:

```
$ yum info mercurial | grep Version
Version     : 2.6.2
```

**Comment by leondz** [comment]
Further details - I'm running under py3.5 to get the latest Keras; this conflicts with mercurial in Conda

```
[ac1ld@sharc-node001 ~]$ conda create -n mercurial_test python=3.5 mercurial
Fetching package metadata .......
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - mercurial -> python 2.6*|2.7*
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.


```

**Comment by mikecroucher** [comment]
+1 for the operating system version. I think we use the OS version for git right?

There is a risk, of course, that the OS won't be updated for slightly longer than forever (Iceberg) and we'll have to subsequently build new versions from source and use modules but I don't see this as a major issue for something like git or mercurial.

**Comment by willfurnass** [comment]
Mercurial should be automatically installed on ShARC's login and worker nodes in the next hour or two.  

Out of curiosity, which version of Keras do you need?

**Comment by leondz** [comment]
Thank you!

We're developing around Keras 2.0.3 right now.

**Comment by willfurnass** [comment]
Hopefully 2.0.3 will be available from the `anaconda` or `conda-forge` conda channels soon, allowing you to set up your software stack without having to install Keras from a Mercurial clone :)
