### ISSUE TITLE
Time limit on qrsh, qsh and qrshx sessions

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/sheffield_hpc#596]
Is there a time limit? @anthonybrookfield ?

If so, we should document at http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/qrsh.html#qrsh and others.

**Comment by willfurnass** [comment]
Added default `h_rt` maximums in PR #600.  Just added info to main page on SGE, not the individual qrsh/qsh/qrshx/qsub pages.

**Comment by mikecroucher** [comment]
@willfurnass I can see the maximums that can be requested but not the defaults if you don't request anything.  Is there a command to ask SGE what this default is?

**Comment by willfurnass** [comment]
@mikecroucher I've noted what I believe to be the correct defaults; I just didn't word my previous comment (and the update to the docs in the PR?) very well.  In that comment I meant that `h_rt` is the maximum duration that your job can run for.

FYI `qconf -sq <somequeuename> | grep h_rt` shows you the default `h_rt` per queue.

**Comment by mikecroucher** [comment]
So if I just do `qrsh` it will last 8 hours?

**Comment by mikecroucher** [comment]
and that's the absolute maximum?

**Comment by anthonybrookfield** [comment]
^ (should be the maximum for interactive jobs in the normal-use queues unless I've forgotten to apply some configs somewhere.... interactive jobs in dedicated queues don't get the limit applied by default...)

**Comment by willfurnass** [comment]
Closing as ShARC to be decommissioned
