### ISSUE TITLE
Install Code Saturne 4.0.7 on ShARC

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#649]
Mandatory dependencies:

- [x] GCC - version?
- [ ] cgns?
- [ ] MED?
- [x] OpenMPI - version?
- [x] HDF5 - version?
- [x] libxml2 - main and devel OS packages installed (2.9.1)

Optional dependencies also wanted:

- [x] Scotch - see #645
- [ ] PT Scotch

Dependencies for GUI:

- [x] qt4 - OS package installed (4.8.5) - need devel package too?
- [ ] pyqt4
- [ ] sip
- [x] python - use OS package (2.7.5)

**Comment by willfurnass** [comment]
@dmrogers75 Enabling GUI support (if needed) might be easiest if pyqt4 and sip are installed under the Code Saturne prefix and `PYTHON_PATH` prepended with their location in the Code Saturne modulefile.  This approach is mentioned at the top of page 7 of the [CS 4.0 documentation](http://code-saturne.org/cms/sites/default/files/docs/4.0/install-4.0.pdf).

**Comment by dmrogers75** [comment]
@willfurnass So should I put pyqt4 and sip in the directory where Code Saturne is to be installed, i.e. /usr/local/packages/apps/codesaturne?
Where and how is qt4 used/activated (assuming it is on Sharc)?
HDF5 is only needed if MED is required; the user requesting the code did not specify MED, only for Scotch and Libxml at the least, with PyQt4 for the GUI. Is HDF5 on Sharc already (it doesn't appear to be)?
Thanks!

**Comment by willfurnass** [comment]
1. Yes, could do (possibly under `$PREFIX/lib/python2.7/site-packages/`)
1. Qt libraries are currently only available using OS packages; see `rpm -qa | grep -i qt` and `rpm -qa qt`.  If you want to compile against these then the Qt4 headers will likeley also need installing (`qt-devel` RPM).  Hope that making CS dependent on the system Qt libs won't cause problems in future - could build a separate Qt4 (and Qt5?) install and make available as a modulefile if there's any doubt.  
1. No, HDF5 is not yet installed on ShARC.

**Comment by dmrogers75** [comment]
Thanks Will.
I have compiled Code Saturne 4.0.7 with scotch/pt-scotch and libxml2 only. I had to recompile scotch with the "-fPIC" cflag as this was requested by CS during its build. If a user requests the other optional packages for the GUI I will attempt to install the python dependent stuff:
I actually tried to install Sip (PyQt4 needs this) in /usr/local/packages/apps/code_saturne/third-party/sip but whatever python/conda I tried it kept complaining about siplib.c:20:20: fatal error: Python.h: No such file or directory  #include <Python.h>

**Comment by willfurnass** [comment]
> it kept complaining about `siplib.c:20:20: fatal error: Python.h: No such file or directory #include <Python.h>`

The python (2.7.5) RPM is installed on ShARC but the Python header files required for compiling SIP are not; they can be found in the `python-devel` RPM (or, if using `conda`, within `${MY_CONDA_ENV_NAME}/include/python${PYTHON_VERS}/Python.h`).

**Comment by willfurnass** [comment]
See http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/code_saturne.html
