### ISSUE TITLE
update docs to prepare for changes to Iceberg scheduler memory limits

### ISSUE THREAD

**Issue by anthonybrookfield** [rcgsheffield/sheffield_hpc#650]
On Iceberg we'll be making a change to the scheduler memory limits configuration:
- 'mem' (virtual memory limits) will no longer be applied (this option will still be accepted but ignored by the scheduler)
- 'rmem' (physical memory limit) will become enforced (previously users received warning emails when this limit was exceeded).

This change will make Iceberg and ShARC behave the same.

**Comment by willfurnass** [comment]
Done.
