### ISSUE TITLE
Update /scratch docs to suggest using $TMPDIR for ease of use/auto-SGE-cleanup ?

### ISSUE THREAD

**Issue by anthonybrookfield** [rcgsheffield/sheffield_hpc#685]
Now that ShARC and Iceberg both have $TMPDIR pointing to /scratch we could advise people to use $TMPDIR in scripts/jobs rather than creating their own /scratch dir.
Advantages:
- unique per job directory created automatically by scheduler
- scheduler removes directory and contents when job finishes
- directory gets created automagically on nodes running slave process

Disadvantages
- for parallel jobs the scheduler will create and then delete TMPDIR at the start/end of each mpirun call... could be a problem for users who do multiple mpiruns within a single job and want data to persist in /scratch between stages
- TMPDIR not set for 'qrsh' sessions.

Anyone have any other thoughts/advantages/disadvantages?

**Comment by willfurnass** [comment]
Use of TMPDIR now documented at  http://docs.hpc.shef.ac.uk/en/latest/hpc/filestore.html (inc. commands for which it is set).
