### ISSUE TITLE
Getting "groups: cannot find name for group ID ###" when using Singularity

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#686]
When running singularity images, users get the error:

```
groups: cannot find name for group ID 20065
```

The group ID varies according to the user, however the ID does not seem to belong to the group associated to the user by default e.g. my group id is 1600 (ac) but when I run `groups` I get an error that it can't find the name for group ID 20089.

While this does not hinder the running of the code, it would be good if we can fix or at least suppress the error. Any ideas?

**Comment by willfurnass** [comment]
Think that group 20089 is created dynamically by SGE for the purposes of tracking resources relating to your SGE job (see `man 8 pam_sge-qrsh-setup`.  The numerical value will differ between concurrent SGE jobs.  If you run `groups` outside the container you'll see a similar error (about the group not having a name).

Somewhat related: https://github.com/singularityware/singularity/issues/552

**Comment by willfurnass** [comment]
See #688

**Comment by twinkarma** [comment]
Not an issue that will break programs. Notes added to documentation to ignore message.
