### ISSUE TITLE
Documentation for Multiple GPUs and Multiple CPU cores

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#690]
The current documentation is not particularly clear about how to submit a job requesting `N` GPUs and `M` GPUs on a single node.

The current documentation suggests that 
+ `-l gpu=N` will request `N` GPUs [source](http://docs.hpc.shef.ac.uk/en/latest/sharc/GPUComputingShARC.html)
+ `-pe smp M` will request `M` CPU cores [source](http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/sge.html)

From this it appears that the way to get `N` GPUs and `M` CPU cores would be `-l gpu=N -pe smp M`, i.e. for `4` GPUs and `4` CPU cores
```
-l gpu=4 -pe smp 4
```

In practice this job will never run, nor progress to an error state, as it seems to actually be requesting 16 GPUs (?) [sge-gpuprolog/prolog.sh:24](https://github.com/RSE-Sheffield/sge-gpuprolog/blob/master/prolog.sh#L24)

To achieve the desired configuration of 4 GPUs and 4 CPUs in a single node, the actual commands must be `-l gpu=1 -pe smp 4`. I've not found this in the documentation anywhere.

Additionally, it doesn't appear possible to request more CPU cores than GPUs, or non multiple ratios? 
i.e. 
+ A heterogeneous application which could use all 40 CPU cores in the DGX-1 whilst using all 8 GPUs
+ A heterogeneous application which uses 4 GPUs, with 1 CPU core per GPU and additionally can use CPU cores for asynchronous host work. I.e. an extra 16 cores, totalling 20 CPUs.

**Comment by willfurnass** [comment]
@ptheywood All the points made above are correct: '-l gpu=x' requests x GPUs per CPU core.  I've clarified this in PR #691 and commented on what CPU+GPU combos are not yet supported (but could be in future if there's enough demand to warrant figuring out how to allow for them).
