### ISSUE TITLE
nvprof cannot output files to /fastdata

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#697]
The nvidia profile (`nvprof`) encounters an issue when attempting to save profiler output to `fastdata`.

An error is reported as follows:

```
==25792== NVPROF is profiling process 25792, command: ./x64/Release/atomicAddBench 4 16 65536 0 0
==25792== Error: Cannot create profiling file: /fastdata/acp14pth/atomicAddBench/atomicAddBench-fastdata.nvvp
```
although a 0 byte file is created.
```
 ls -l /fastdata/acp14pth/atomicAddBench/
total 0
-rw-r--r-- 1 acp14pth ac 0 Aug 16 14:13 atomicAddBench-fastdata.nvvp
```

This is not an issue for `/home/` or `/data/`.

The issue should be reproducible using the `sharc-profiling` branch of my `atomicAddBench` repository (here)[https://github.com/ptheywood/atomicAddBench/tree/sharc-profiling] by:

1. Connect to ShARC via SSH, and launch an interactive session on any worker node (for compilation)
2. `git clone https://github.com/ptheywood/atomicAddBench.git`
3. `git checkout sharc-profiling`
4. `cd atomicAddBench`
4. `module load libs/CUDA/8.0.44/binary` to load CUDA, specifically `nvcc`
5. `./make.sh` to compile the example code.
6. `qsub atomicAddBench.job.sh`
    + This assumes you are a user with access to the DGX-1, although with a minor change to the job file this should work with any GPU enabled node.
7. Wait for the job to complete, and inspect both `/fastdata/$USER/atomicAddBench/atomicAddBench-fastdata.nvvp` and `~/atomicAddBench/log.txt`.

The logfile should be similar to https://github.com/ptheywood/atomicAddBench/blob/sharc-profiling/log.txt

I do not believe this to be a permissions related issue, as the file is actually created, and the permissions on `/fastdata/acp14pth/` are more permissive than `/data/acp14pth/`

I feel this either needs investigating, or simply documenting that `nvprof` cannot output to `fastdata`.

**Comment by willfurnass** [comment]
This could be due to the Lustre filesystem on /fastdata not supporting file
locking. This lack of file locking causes for certain other apps/libs e.g.
sqlite. If you need fast storage on a single node then haeve you considered
using local /scratch storage? This is provided using a ext4 filesystem
(that supports file locking)?

**Comment by ptheywood** [comment]
I don't need it to be on `/fastdata` in particular, i just encountered the issue and felt it worth reporting. 
The profiler output is (typically) small, so home and data storage is sufficient, but others may run into this issue. 

I believe that nvprof output files are essentially sqlite databases, which would explain the issue.

**Comment by willfurnass** [comment]
Do you think [this page](http://docs.hpc.shef.ac.uk/en/latest/sharc/software/libs/cuda.html) be the most obvious place to document this issue?

**Comment by ptheywood** [comment]
Yes that seems like the most appropriate place, as it's for profiling CUDA applications (and requires the CUDA module to be loaded)
