### ISSUE TITLE
Gromacs 2016.1 on Iceberg/ShARC

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#707]
GPU and CPU builds for Iceberg previously requested by a user.

For efforts made to install on Iceberg (inc. documentation, install scripts and module files) see the `ENH_newer_gromacs` branch in this repo.

Test module files can be found on Iceberg:
```
$ module avail |& grep gromacs
apps/gcc/4.9.2/gromacs/2016.1-cuda-8.0.44-TESTING
apps/gcc/4.9.2/gromacs/2016.1-serial-TESTING
apps/intel/15/gromacs/5.1.2
apps/intel/15/gromacs/5.1.2-cuda-7.5.18  
```

Note that the aforementioned branch has not yet been merged nor the `-TESTING` suffix removed from the Iceberg module file names as I previously couldn't get all of Gromacs' regression tests to pass using:

```
./gmxtest.pl -nt $OMP_NUM_THREADS all -noverbose
```

Once set up properly on Iceberg the install scripts and modulefiles can hopefully easily be adapted to set up Gromacs on ShARC.

**Comment by dmrogers75** [comment]
Gromacs 2016.4 installed on Sharc. Two compilations; one with GPU support and one without; both with OpenMP parallelism. Both passed the "make check" regressions tests as part of the installation.

apps/gromacs/2016.4/gcc-4.9.4
apps/gromacs/2016.4/gcc-4.9.4-cuda-8.0

**Comment by willfurnass** [comment]
@dmrogers75 Excellent.  Can this Issue be closed?

**Comment by dmrogers75** [comment]
@willfurnass Yes, I shall close.
