### ISSUE TITLE
R 3.5.1

### ISSUE THREAD

**Issue by markdunning** [rcgsheffield/sheffield_hpc#825]
We are now up to R version 3.5.1 (released 2018-07-02) whereas the most recent R module on sharc is 3.4.0 (released 2017-04-21). 

Can we have a new module for R 3.5.1 please?

**Comment by willfurnass** [comment]
Installed by @desmfryan; see 
* http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/R.html
* http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/intel_r.html
