### ISSUE TITLE
Install LAMMPS Molecular Dynamics Simulator on ShARC

### ISSUE THREAD

**Issue by WSFall** [rcgsheffield/sheffield_hpc#836]
Why is this not installed on ShARC?  I am aware of a few people who could really make use of this.

https://lammps.sandia.gov

**Comment by desmfryan** [comment]
We have not had any requests to install this software on the HPC (I have been working here 20 months).

**Comment by WSFall** [comment]
Could we have it installed if there is sufficient demand?

**Comment by mikecroucher** [comment]
@WSFall Could you install this yourself in your /home or /data directories.  If I were in your position, I'd first consider using something like conda.

Create yourself a conda environment for this application following the instructions at 

http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/python.html

and then try the following to install LAMMPS into the environment

https://anaconda.org/pyiron/lammps

Note: I've not tried this myself.
Hope this helps,
Mike

**Comment by shuvo-dip** [comment]
I'm currently using LAMMPS on my machine with small time scale. Our group is trying to shift on LAMMPS, so we need LAMMPS on cluster. If you can install it on ShARC that would be really helpful.
Thanks @WSFall for raising the issue.

**Comment by WSFall** [comment]
@shuvo-dip No problem at all. @mikecroucher thanks, I could give that a try! What about others, there must be more users throughout the university that can make use of this. @desmfryan it would be great if we could have this installed. There are likely more users but not all subscribe to HPC emails or have a

**Comment by aaronrfinnney** [comment]
I use my own installed version of this code on ShARC. It is easily the fastest growing application for classical MD (with very broad community support) and contains lots of functionality that surpasses other common codes like DL_POLY. An fully optimised compilation on the machine would be welcomed.

I often use this code and DL_POLY interfaced with Plumed (http://www.plumed.org/) for free energy calculations. Plumed is a plug in for a number of classical and DFT MD codes that is used by a number of people in MSE.

**Comment by Rhodahawkins** [comment]
Having LAMMPS installed on ShARC would be beneficial to my research group.

Dr Rhoda J Hawkins
Department of Physics & Astronomy
University of Sheffield
F36, Hicks Building, Hounsfield Road
Sheffield S3 7RH, UK
tel: +44 (0)114 22 24524
http://rhoda-hawkins.staff.shef.ac.uk

**Comment by willfurnass** [comment]
Installed by @desmfryan; see http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/lammps.html
