### ISSUE TITLE
Install CUDA 10.0

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#883]
CUDA 10.0 was released in 2018 and is now being adopted by popular packages such as Tensorflow. 

It would be good to have this installed on ShARC (not required for Iceberg). This will require a driver update.

https://github.com/RSE-Sheffield/GPUComputing/issues/16

**Comment by willfurnass** [comment]
NVIDIA driver 410.104 is recommended for CUDA 10.0 and P100 and/or K80 GPUs.

**Comment by willfurnass** [comment]
New driver and CUDA 10.0 installed on ShARC.  Cc @ptheywood @twinkarma

**Comment by ptheywood** [comment]
I'll make a PR to update the relevant docs.

**Comment by willfurnass** [comment]
Great.  Closing.
