### ISSUE TITLE
Install CUDA 10.1 on ShARC

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#884]
CUDA 10.1 has been released as of 2019-02-27, which would be useful to have on ShARC. 

There is not yet an appropriate driver for the GPUs in ShARC, so this will have to wait until Nvidia release the appropriate drivers.

**Comment by ptheywood** [comment]
A recommended driver for Tesla GPUs (incl. V100, P100 and K80) and CUDA 10.1 is now available - `418.40.04` released on `2019.3.25`.

https://www.nvidia.co.uk/Download/driverResults.aspx/144789/en-uk

**Comment by willfurnass** [comment]
NVIDIA driver 418.40.04 currently in the process of being installed on ShARC's GPU nodes.

**Comment by willfurnass** [comment]
Many nodes now using the new driver but some still on the old one being drained of jobs prior to a reboot.
