### ISSUE TITLE
Install FSL

### ISSUE THREAD

**Issue by ravibir** [rcgsheffield/sheffield_hpc#885]
I've been given access to ShARC to complete my dissertation. In order to process brain images I need to use the FSL software, so could this please be added to ShARC. Thankyou.

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation#Installing_FSL

**Comment by willfurnass** [comment]
@ravibir The quickest way of getting this installed on ShARC could be to install it using `conda` from the `conda-forge` channel: https://anaconda.org/conda-forge/fslpy  Have you used conda to install packages on ShARC before?

**Comment by ravibir** [comment]
No I haven't done that yet. I'm using MobaXterm to connect to ShARC, so would I first load conda Python in the terminal with
module load apps/python/conda

and then install fsl with
conda install -c conda-forge fslpy
?

**Comment by willfurnass** [comment]
@ravibir You should create a conda environment for installing fslpy into, so you want something like

```sh
ssh USERNAME@sharc.shef.ac.uk
qrshx  # to start an interactive session on a worker node
module load apps/python/conda
conda create -n my-fslpy-env -c conda-forge fslpy
source activate my-fslpy-env
```

In subsequent interactive sessions and batch jobs you don't need to re-run the `conda create` command.  

See http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/python.html#creating-an-environment for more info.

**Comment by ravibir** [comment]
Thanks for your help so far. I've done all of this and tried to run the FSL program fsleyes but it says it wasn't found. I assumed this is because FSL hasn't installed yet, so I downloaded and ran the fslinstaller.py file found on their website. It asks me to enter a password before installation but every password I try, such as my university password and computer password, seems to be incorrect. Am I doing the right thing and if so do you know what the password would be?

**Comment by willfurnass** [comment]
Hmm, the only executable the `fslpy` conda package installs is called `fsl_ents`; there's no program called `fsleyes`:

```console
$ conda create -n my-fsl-env -c conda-forge fslpy
$ . activate my-fsl-env
$ ls ${CONDA_PREFIX}/bin/fsl*
/home/will/miniconda3/envs/my-fsl-env/bin/fsl_ents
```

---

If you're going to try to use `fslinstaller.py` instead then you'll need to provide `-d` and possibly the `-e` parameters when running that Python script (see https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Linux); otherwise the installer will try to write files to directories that you don't have write access to.

**Comment by ravibir** [comment]
It seems like I have to use the full fslinstaller.py install as I need a few of the things that aren't in fslpy.  I managed to change the directory to one I have access to, however the -e parameter keeps returning an error. Although without this parameter it starts to download and install but returns the error below

[aca16rsb@sharc-node004 ~]$ python fslinstaller.py -d /home/aca16rsb/fsl

Downloading...
Checking FSL package
[OK] File downloaded
Installing FSL software version 6.0.1...
[FAILED] Unable to unpack FSL - Unable to unpack FSL.

I've searched online but can't seem to find what this means. Do you know how I would fix this?

**Comment by willfurnass** [comment]
I've also tried and failed to get `fslinstaller.py` working. 

---

Let's try another approach: I've build a [Singularity image](http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/singularity.html) containing the latest FSL.  You can download and start using this as follows:

```
ssh USERNAME@sharc
qrshx
export SINGULARITY_CACHEDIR="/fastdata/$USER/singularity_cache"
mkdir -p "${SINGULARITY_CACHEDIR}"
singularity pull --name fsl-debian-stretch-singularity-latest.sif shub://rses-singularity/fsl-debian-stretch-singularity:latest 
singularity exec "${SINGULARITY_CACHEDIR}/fsl-debian-stretch-singularity-latest.sif" /bin/bash
```

After running `singularity exec` you are then able to run commands 'within' a FSL 'container' e.g. `fsl-selftest` or `fsl5.0-gps`.  Note that most FSL commands start with `fsl5.0-`.

Also:
 - You should add `SINGULARITY_CACHEDIR="/fastdata/$USER/singularity_cache"` to your `.bashrc` file to ensure that this shell variable is set every time you log on to ShARC.
 - In the instructions above we 'pull' the image from an online repository and save the file on `/fastdata`; files on this filesystem are [deleted 60 days after creation](http://docs.hpc.shef.ac.uk/en/latest/hpc/filestore.html).  
 - If you want to see how the Singularity image for FSL was built, click the 'recipe' link [here](https://www.singularity-hub.org/collections/2514).

Let me know if this works for you.

**Comment by ravibir** [comment]
I've done everything you've said in the terminal. When I run fsl-selftest it runs and says all the tests have passed, but when I try and run anything else is says command not found eg

aca16rsb@sharc-node003:~/Dissertation/patient01$ fs15.0-gps
bash: fs15.0-gps: command not found

Am I running the commands correctly? The main 2 things I need in fsl are fsleyes and BIANCA, but when I try running them using the method below again it comes up with command not found.

aca16rsb@sharc-node003:~/Dissertation/patient01$ fsleyes patient01_T1W.nii.gz
bash: fsleyes: command not found

**Comment by willfurnass** [comment]
@ravibir Ah, the method I suggested previously installs a version of FSL that predates BIANCA.  Let's revert to trying to get FSL installed with `fslinstaller.py`.  Please try the following - this seems to work for me but I haven't given it extensive testing:

```sh
FSLVERS=6.0.1
python fslinstaller.py -V $FSLVERS -d /data/$USER/fsl-$FSLVERS
source $HOME/.bash_profile
```

**Comment by ravibir** [comment]
This seems to work and I can now use fsleyes successfully. However when I type in bianca it comes up with the error

[aca16rsb@sharc-node004 Dissertation]$ bianca
/usr/bin/env: fslpython: No such file or directory

Do you know how to fix this?
Thanks

**Comment by willfurnass** [comment]
What do the following commands show?

```bash
echo $FSLDIR
echo $PATH
which fslpython
```

**Comment by ravibir** [comment]
echo $FSLDIR
/data/aca16rsb/fsl-6.0.1

echo $PATH
/data/aca16rsb/fsl-6.0.1/bin:/usr/local/sge/live/bin/lx-amd64:/usr/local/sge/live/bin/lx-amd64:/usr/local/scripts/:/usr/lib64/qt-3.3/bin:/scratch/3673986.1.interactive.q:/usr/local/bin:/bin:/usr/bin:/opt/puppetlabs/bin:/home/aca16rsb/bin

which fslpython
no fslpython in (/data/aca16rsb/fsl-6.0.1/bin:/usr/local/sge/live/bin/lx-amd64:/usr/local/sge/live/bin/lx-amd64:/usr/local/scripts/:/usr/lib64/qt-3.3/bin:/scratch/3673986.1.interactive.q:/usr/local/bin:/bin:/usr/bin:/opt/puppetlabs/bin:/home/aca16rsb/bin)

**Comment by willfurnass** [comment]
What is in `~/.bash_profile`?  Does it include the following?

```bash
FSLDIR=/usr/local/fsl
. ${FSLDIR}/etc/fslconf/fsl.sh
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH
```

**Comment by ravibir** [comment]
My bash profile contains

# FSL Setup
FSLDIR=/data/aca16rsb/fsl-6.0.1
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH
. ${FSLDIR}/etc/fslconf/fsl.sh

When I change it to 
FSLDIR=/usr/local/fsl
. ${FSLDIR}/etc/fslconf/fsl.sh
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH

Then source $HOME/.bash_profile comes up with the error No such file or directory

**Comment by willfurnass** [comment]
Can you move the following lines from `~/.bash_profile` to the end of your `~/.bashrc` file:
```
FSLDIR=/data/aca16rsb/fsl-6.0.1
PATH=${FSLDIR}/bin:${PATH}
export FSLDIR PATH
. ${FSLDIR}/etc/fslconf/fsl.sh
```
then run
```
source ~/.bashrc
which fslpython
```
What's the output?

**Comment by ravibir** [comment]
The output is

/usr/bin/which: no fslpython in (/data/aca16rsb/fsl-6.0.1/bin:/usr/local/sge/live/bin/lx-amd64:/data/aca16rsb/fsl-6.0.1/bin:/usr/local/sge/live/bin/lx-amd64:/usr/local/sge/live/bin/lx-amd64:/usr/local/scripts/:/usr/lib64/qt-3.3/bin:/scratch/3686846.1.interactive.q:/usr/local/bin:/bin:/usr/bin:/opt/puppetlabs/bin:/home/aca16rsb/bin)

**Comment by willfurnass** [comment]
I don't think FSL is properly installed in your `/data/$USER` directory; here's what I get when I run that `find` command against my install:
```console
[te1st@sharc-login1 ~]$ find /data/$USER/fsl-6.0.1/ -name fslpython
/data/te1st/fsl-6.0.1/bin/fslpython
/data/te1st/fsl-6.0.1/fslpython
/data/te1st/fsl-6.0.1/fslpython/envs/fslpython
```
I suggest you delete your `/data/$USER/fsl-6.0.1/ ` directory and reinstall.

**Comment by ravibir** [comment]
I reinstalled it and BIANCA can now be called. However when I do an example BIANCA call it stops running and returns an error. Do you know why is returns this error? I've pasted it in the section below. Thanks

**Comment by ravibir** [comment]
[aca16rsb@sharc-login1 Dissertation]$ bianca --singlefile=document --labelfeaturenum=3 --brainmaskfeaturenum=1 --querysubjectnum=5 --trainingnums=1,2,3,4 --featuresubset=1,2
/data/aca16rsb/fsl-6.0.1/bin/bianca:558: DeprecationWarning: get_header method is deprecated.
Please use the ``img.header`` property instead.

* deprecated from version: 2.1
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
  GlobalOpts.pixdims=imobj.get_header().get_zooms()
Traceback (most recent call last):
  File "/data/aca16rsb/fsl-6.0.1/bin/bianca", line 1033, in <module>
    p_main()
  File "/data/aca16rsb/fsl-6.0.1/bin/bianca", line 1006, in p_main
    [idvals,distvals] = call_knn(k_tree,check_dat)
  File "/data/aca16rsb/fsl-6.0.1/bin/bianca", line 310, in call_knn
    distances, indices = k_tree.kneighbors(check_dat)
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/neighbors/base.py", line 455, in kneighbors
    for s in gen_even_slices(X.shape[0], n_jobs)
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/aca16rsb/fsl-6.0.1/fslpython/envs/fslpython/lib/python3.7/site-packages/sklearn/neighbors/base.py", line 292, in _tree_query_parallel_helper
    return tree.query(data, n_neighbors, return_distance)
  File "sklearn/neighbors/binary_tree.pxi", line 1320, in sklearn.neighbors.kd_tree.BinaryTree.query
  File "sklearn/neighbors/binary_tree.pxi", line 596, in sklearn.neighbors.kd_tree.NeighborsHeap.__init__
MemoryError

**Comment by willfurnass** [comment]
You shouldn't be running bianca (or any non-trivial tasks) on ShARC's login nodes - see http://docs.hpc.shef.ac.uk/en/latest/hpc/scheduler/sge.html for info on how to start an interactive session or run a batch job with a specified amount of memory.

**Comment by ravibir** [comment]
I think I've finally got it working!
Thankyou very much for all you're help. I'll message again if any other issues come up

**Comment by zrsroxanne** [comment]
> What do the following commands show?
> 
> ```shell
> echo $FSLDIR
> echo $PATH
> which fslpython
> ```

Excuse me, I'm getting the same error when running bianca /usr/bin/env: ‘fslpython’: No such file or directory.
I couldn't use fsleyes before, but I set up an fslpython environment under anaconda3 and used a script for a soft connection

#! /bin/bash

for link in $(ls $1)
do
        echo $link
        ln -s $1/$link $2/$link
done

touch softlink.sh
bash test.sh /home/zrs/anaconda3/envs/fslpython/bin/ /home/zrs/fsl/bin
But I still can't run bianca. Please have you ever encountered this kind of problem before, thanks in advance
