### ISSUE TITLE
Mathematica on Sharc please

### ISSUE THREAD

**Issue by EWinstanley** [rcgsheffield/sheffield_hpc#895]
My PhD students and I make extensive use of mathematica on iceberg, where it works well.  Since iceberg is being shut down with bessemer coming online, please can mathematica be installed on sharc?  It's essential for my research.

Many thanks,
Elizabeth Winstanley

**Comment by willfurnass** [comment]
Mathematica is now on ShARC: https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/mathematica.html
