### ISSUE TITLE
Singularity can't pull and image, missing mksquashfs

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#953]
I tried to pull an image from docker hub but getting the problem below:

```
$ singularity pull docker://chaste/chaste-docker:latest
INFO:    Converting OCI blobs to SIF format
FATAL:   While making image from oci registry: while building SIF from layers: unable to create new build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH
```

**Comment by willfurnass** [comment]
`mksquash` is in `/usr/sbin`, which isn't on the default `PATH` for most users (was it ever?  how did this work before now?).  Try `export PATH=/usr/sbin:$PATH` as a temporary workaround.

**Comment by twinkarma** [comment]
I've always just built images on my local machine and scp it to ShARC so never knew that this was the problem.

**Comment by anthonybrookfield** [comment]
Looks like singularity.conf has an option for just this kind of eventuality
```
#MKSQUASHFS PATH: [STRING]
#DEFAULT: Undefined
```
I've set it to:
```
mksquashfs path = /usr/sbin/mksquashfs
```

Pulling from dockerhub seems to work following this change
```
$ singularity pull docker://chaste/chaste-docker:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
.....
INFO:    Creating SIF file...
INFO:    Build complete: chaste-docker_latest.sif
```
Change should be applied across ShARC now.  Does this fix things for you?

**Comment by twinkarma** [comment]
Yes, seems to be working now
