### ISSUE TITLE
Modern Nvidia profiling tools on Bessemer

### ISSUE THREAD

**Issue by ptheywood** [rcgsheffield/sheffield_hpc#955]
GPUs in Bessemer are modern enough to make use of the newer profiling tools provided by Nvidia, Nsight Systems and Nsight Compute which support SM62 and newer devices (Volta and above in the Tesla range)

These  tools are installed with CUDA, but reside in subfolders so are not neccesarily added to the path by default. 

It would be useful for these to be made available to users in the relevant module file(s)

The relevant binary for Nsight Systems is `nsight-sys`, located in `$CUDA_HOME/NsightSystems-2018.3/Host-x86_64/` for CUDA 10.1.105 on Bessemer.

The relevant binary for Nsight Compute is `nv-nsight-cu-cli` located in `$CUDA_HOME/NsightCompute-2019.1/` for CUDA 10.1.105 on Bessemer.

I'll add some documentation on usage once the bessemer docs are in place / the tools are available.

**Comment by willfurnass** [comment]
Is this distinct from `$CUDA_HOME/bin/nsight`?

**Comment by ptheywood** [comment]
Yep they are different, `$CUDA_HOME/bin/nsight` is an nvidia-modified version of eclipse as a CUDA IDE.

Looking at my local machine (Ubuntu 16.04), it does appear that `nv-nsight-cu-cli` and `nsight-sys` are both in `$CUDA_HOME/bin` for CUDA 10.1.243, which I think is the CUDA 10.1 Update 2, so this may not be needed for future CUDA versions.

**Comment by willfurnass** [comment]
> Looking at my local machine (Ubuntu 16.04), it does appear that `nv-nsight-cu-cli` and `nsight-sys` are both in `$CUDA_HOME/bin` for CUDA 10.1.243, which I think is the CUDA 10.1 Update 2, so this may not be needed for future CUDA versions.

Yeah, that's the case for the 10.1u2 and 10.2 installs I'm doing on ShARC (PR #1002)

**Comment by willfurnass** [comment]
CUDA 10.1.243, which has the desired links to the profiling tools in `$CUDA_HOME/bin`, will be available when the `fosscuda-2019b` EasyBuild toolchain is installed in the live area and PR #1000 is merged.

**Comment by ptheywood** [comment]
As an extra note, nsight-compute is not useful on ShARC, as it is only supported by compute capability `6.1` and above (i.e. V100 and T4 currently in the tesla range). 

Nsighty-systems is usable, but not as useful without nsight-compute to complement it.

CUDA 10.0 only ships with nsight-compute, not nsight sytems so I think it's fine to not modify the modulefile to  support this, and just close this with no explicit changes other than the CUDA 10.1.243 installation.

**Comment by willfurnass** [comment]
@ptheywood NB would be good to get your input on what docs are required for nsight-compute on Bessemer and on private ShARC V100 nodes.

**Comment by ptheywood** [comment]
I didn't realise there were any V100 nodes in ShARC? (I thought all the private nodes were P100, although I could easily be wrong).

I'm happy to add some docs on making use of the new profiling tools at some point (probably once the new bessemer nodes are up so that I can test things).  

I previously wrote some very basic notes for last years GPU hackathon which could easily be adapted / expanded: https://github.com/GPUHackSheffield/Documentation/blob/master/tools/cuda-profiling-for-hpc.rst

**Comment by willfurnass** [comment]
Yep:
```
$ qhost -F gpu_arch | grep v100
    Host Resource(s):      hf:gpu_arch=nv-v100
    Host Resource(s):      hf:gpu_arch=nv-v100
```
