### ISSUE TITLE
Request for Gaussian 09 on Bessemer

### ISSUE THREAD

**Issue by me1cmpa** [rcgsheffield/sheffield_hpc#962]
If at all possible, could the Gaussian 09 / GaussView program be installed on Bessemer?
 
There are a number of post-graduate students and research associates in our cluster who could make use of this if it could be installed.

Thankyou,

**Comment by jkwmoore** [comment]
This is available, please see: https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/gaussian.html
