### ISSUE TITLE
OpenCV on Sharc and Bessemer

### ISSUE THREAD

**Issue by XianyuanLiu** [rcgsheffield/sheffield_hpc#985]
Hi,

I need to adopt opencv3 or opencv4 to build my research environment. However, I can not find how to load OpenCV in Sharc. I can not install it via conda or pip, because I don't have access. Could you please help me with that?

Thanks in advance!

**Comment by willfurnass** [comment]
You should be able to create conda environments containing OpenCV on both ShARC and Bessmer:

## Bessemer

```sh
# Log on to Bessemer
ssh username@bessemer.shef.ac.uk
# Start an interactive session
srun --pty /bin/bash
# Load a version of conda (see https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/python.html)
module load Anaconda3/5.3.0
# Create a new conda environment
conda create -n my_opencv_env python=3.6
# Activate this new environment
source activate my_opencv_env  
# Install OpenCV 3
conda install opencv=3
# OR OpenCV 4
conda install -c conda-forge opencv=4
# NB we need to install OpenCV 4 from the conda-forge conda channel as it's not yet available from the default conda package channel.
```

## ShARC 

```
# Log on to ShARC
ssh username@sharc.shef.ac.uk
# Start an interactive session
qrshx
# Load a version of conda (see https://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/python.html)
module load apps/python/conda
# Create a new conda environment
conda create -n my_opencv_env python=3.6
# Activate this new environment
source activate my_opencv_env  
# Install OpenCV 3
conda install opencv=3
# OR OpenCV 4
conda install -c conda-forge opencv=4

**Comment by willfurnass** [comment]
Cc @haipinglu re ^

**Comment by haipinglu** [comment]
Thanks a lot Will!

Kind regards,

Haiping @ http://staffwww.dcs.shef.ac.uk/people/H.Lu/
Senior Lecturer in Machine Learning, University of Sheffield

**Comment by XianyuanLiu** [comment]
Thanks a lot! However, I cannot finish that successfully!

$ conda install opencv=3
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /usr/local/packages/apps/conda/envs/anaconda3-4.2.0:

The following NEW packages will be INSTALLED:

    blas:   1.0-mkl          
    opencv: 3.1.0-np111py35_1

Proceed ([y]/n)? y

CondaIOError: IO error: Missing write permissions in: /usr/local/packages/apps/conda
#
# You don't appear to have the necessary permissions to install packages
# into the install area '/usr/local/packages/apps/conda'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_anaconda3-4.2.0 --clone="/usr/local/packages/apps/conda/envs/anaconda3-4.2.0

**Comment by willfurnass** [comment]
You need to create your own conda environment and activate it before you're able to install any conda packages on ShARC/Bessemer (at least, you do if you're using `module load` to provide a version of conda).  In your example above you're trying to install packages into the *root* (aka *base*) conda environment, which is effectively immutable for everyone but system administrators.

If you'd like to discuss ways of using conda on HPC I recommend booking a Code Clinic session: https://rse.shef.ac.uk/support/code-clinic/
